### ISSUE TITLE
failing postinstall

### ISSUE THREAD

**Issue by AaronNGray** [MichalLytek/type-graphql#1019]
**Describe the Bug**

Failing to install with Node.js LTS.

**To Reproduce**
```
git clone https://github.com/MichalLytek/type-graphql
npm install
```

**Expected Behavior**

Normal install

**Logs**

```
C:\Users\aaron\GitHub\type-graphql>npm install
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated graphql-toolkit@0.5.16: Use @graphql-toolkit/* monorepo packages instead. Check https://github.com/ardatan/graphql-toolkit for more details
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

> type-graphql@0.0.0-unreleased postinstall
> node ./dist/postinstall || exit 0

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\aaron\GitHub\type-graphql\dist\postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

added 1300 packages, and audited 1301 packages in 1m

70 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (15 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
**Environment (please complete the following information):**

- OS: [e.g. Windows]
Windows 10
- Node (e.g. 10.5.0)
14.17.6, includes npm 6.14.15
- Package version [e.g. 0.12.2] (please check if the bug still exist in newest release)
master
- TypeScript version (e.g. 2.8.2)
4.4.3

**Additional Context**

Getting same with checking out v1.1.1

**Comment by MichalLytek** [comment]
This is expected. Postinstall is for downloading package from npm. So because of the folder structure it does not work when you git clone.

**Comment by AaronNGray** [comment]
Gosh thats a bit of a bodge somewhere in the system, is that why the project Build label is says the project fails ? What do other projects do ?
