### ISSUE TITLE
You use an incorrect version of the 'graphql' package: "16.0.0"

### ISSUE THREAD

**Issue by enheit** [MichalLytek/type-graphql#1099]
**Describe the Bug**

After updating `graphql` dependency to the current latest version 16.0.0, the following error occurs on my project start up. Is there any possibility to use your lib (type-graphql) with latest version of `graphql`? 

As far I understand I must use previous version of `graphql@15.3.0`?

```
Failed to start apollo servider UnmetGraphQLPeerDependencyError: Looks like you use an incorrect version of the 'graphql' package: "16.0.0". Please ensure that you have installed a version that meets TypeGraphQL's requirement: "^15.3.0".
    at Object.ensureInstalledCorrectGraphQLPackage (C:\projects\project-api\node_modules\type-graphql\dist\utils\graphql-version.js:20:15)
    at Function.checkForErrors (C:\projects\project-api\node_modules\type-graphql\dist\schema\schema-generator.js:47:27)
    at Function.generateFromMetadataSync (C:\projects\project-api\node_modules\type-graphql\dist\schema\schema-generator.js:26:14)        
    at Function.generateFromMetadata (C:\projects\project-api\node_modules\type-graphql\dist\schema\schema-generator.js:16:29)
    at buildSchema (C:\projects\project-api\node_modules\type-graphql\dist\utils\buildSchema.js:10:61)
    at Object.<anonymous> (C:\projects\project-api\src\infrastructure\graphql\schema.graphql.ts:54:41)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\projects\project-api\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\projects\project-api\node_modules\ts-node\src\index.ts:1374:12)
```

**To Reproduce**
1. Install `graphql@16.0.0`  and `type-graphql@1.1.1`.
2. Run the project

**Expected Behavior**
`type-graphql` should work with `graphql@16.0.0`

**Environment:**

- OS: Windows 11
- Node: v14.16.0
- Package version: ^1.1.1
- TypeScript version: ^4.4.4

**Comment by MichalLytek** [comment]
Yes, GraphQL 16 has a lot of breaking changes. TypeGraphQL is tightly coupled so you must follow the npm peer deps (you've ignored them). 

That's why the runtime version check kicked in, because otherwise I would have 15734 issues about `cannot read property xyz of undefined` 😛 

Closing this one as I will create by myself a thread about upgrading to GraphQL v16.
