### ISSUE TITLE
Error: Unable to find type metadata for input type or object type named ''

### ISSUE THREAD

**Issue by margunwa123** [MichalLytek/type-graphql#1152]
**Describe the Bug**
After adding the Post model to schema.prisma, my server stopped working. I got the error 
`Error: Unable to find type metadata for input type or object type named ''`
the error comes from line 168 in type-graphql/dist/metadata/metadata-storage.js.

**To Reproduce**
Clone the github repository https://github.com/margunwa123/prisma-typegraphql-auth 
Then create a .env file in the root, the content are:
```
#! APP CONFIG
PORT=3500
DATABASE_URL=postgresql://admin:admin@postgres-typegraphql:5432/prisma-typegraphql?schema=public

#! POSTGRES CONFIG
POSTGRES_USER=admin
POSTGRES_PASSWORD=admin
POSTGRES_DB=prisma-typegraphql


#! PGADMIN CONFIG
PGADMIN_DEFAULT_EMAIL=admin@admin.com
PGADMIN_DEFAULT_PASSWORD=root
```
then run `yarn dev`. 

**Expected Behavior**
It should work

**Logs**
```sh
/app/node_modules/type-graphql/dist/metadata/metadata-storage.js:168
        definitions.forEach(def => {
                    ^
Error: Unable to find type metadata for input type or object type named ''
    at /app/node_modules/type-graphql/dist/metadata/metadata-storage.js:184:27
    at Array.forEach (<anonymous>)
    at MetadataStorage.buildFieldResolverMetadata (/app/node_modules/type-graphql/dist/metadata/metadata-storage.js:168:21)
    at MetadataStorage.build (/app/node_modules/type-graphql/dist/metadata/metadata-storage.js:101:14)
    at Function.generateFromMetadataSync (/app/node_modules/type-graphql/dist/schema/schema-generator.js:28:51)
    at Function.generateFromMetadata (/app/node_modules/type-graphql/dist/schema/schema-generator.js:16:29)
    at buildSchema (/app/node_modules/type-graphql/dist/utils/buildSchema.js:10:61)
    at /app/src/index.ts:17:35
    at step (/app/src/index.ts:33:23)
    at Object.next (/app/src/index.ts:14:53)
[nodemon] app crashed - waiting for file changes before starting...
```

**Environment (please complete the following information):**
- OS: Ubuntu
- Node 16.10.0
- Package version 1.1.1
- TypeScript version 4.5.4

Any help will be much appreciated, Thank you in advance!

**Comment by margunwa123** [comment]
It is funny how I solved the problem one or two minutes after I have posted it to the issues lol.
**How To Solve:**
My tsconfig.json has these lines:
```json
{
  "lib": ["esnext"],
  "target": "ES5"
}
```
replace it with these lines:
```json
{
    "target": "ES2018",
    "lib": ["es2018"],
}
```
