### ISSUE TITLE
Error: "User" defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by pranta-barua007** [MichalLytek/type-graphql#1273]
**Describe the Bug**
Repo --> https://github.com/pranta-barua007/graphql-microservice-typescript
i have copied the graphql v16 branch of apollo-federation example made a separated working repo. After all of polishing, the error shows that `Error: "User" defined in resolvers, but not in schema`

**To Reproduce**
step 1 --> npm i
step 2 --> npm run dev

**Expected Behavior**
a log on console `Apollo Gateway ready at ${url}` 

**Logs**
Error: "User" defined in resolvers, but not in schema
    at addResolversToSchema (/home/pranto/projects/graphql-microservice-typescript/node_modules/@graphql-tools/schema/index.js:135:19)
    at buildFederatedSchema (/home/pranto/projects/graphql-microservice-typescript/helpers/buildFederatedSchema.ts:24:25)
    at async Object.listen (/home/pranto/projects/graphql-microservice-typescript/accounts/index.ts:9:18)
    at async bootstrap (/home/pranto/projects/graphql-microservice-typescript/index.ts:14:34)
[nodemon] clean exit - waiting for changes before restart

**Environment (please complete the following information):**

- OS: [Windows 10 pro 21H2]
- Node (v16.14.2)
- Package version (copied the `src` folder for support of graphql 16)
- TypeScript version (^4.6.3)

**Additional Context**

**Comment by MichalLytek** [comment]
Please do not report yet that wip branches are not working.

**Comment by pranta-barua007** [comment]
@MichalLytek  thanks for the response.  would love to know by when it will be ready?
