### ISSUE TITLE
Error: Subscription field must return Async Iterable. Received: undefined.

### ISSUE THREAD

**Issue by V1os** [MichalLytek/type-graphql#1362]
**Describe the Bug**
Error after subscription client

**To Reproduce**
```
/// server
import { ApolloServer } from 'apollo-server-express';
import express from 'express';
import { useServer } from 'graphql-ws/lib/use/ws';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
/// ...

  const app = express();
  const httpServer = createServer(app);
  const wsServer = new WebSocketServer({
    server: httpServer,
    path: '/',
  })

  const schema = buildFederatedSchema({ orphanedTypes, resolvers, pubSub })
  const serverCleanup = useServer({ schema }, wsServer);
  const server = new ApolloServer({ schema });
  
  await server.start();
  server.applyMiddleware({ app, path: '/' });
  httpServer.listen({ port }, ... );


/// resolver

@Resolver()
export class SubscriptionResolver {
  @Subscription(() => Notification, {
    subscribe: withFilter(
      () => pubSub.asyncIterator(topics),
      (root, args) => {
        return args.type === root.type;
      },
    ),

    // subscribe() {
    //   return pubSub.asyncIterator(topics);
    // },

    // topics,
    // topics: ({ args }) => args.type,
    
    // filter: ({ args, payload }) => {
    //   return args.type === payload.type;
    // },
  })
  notifications(@Root() payload: NotificationPayload, @Args() args: NotificationArgs) {
    return {
      type: args.typeNotify,
      date: payload.date,
      meta: payload?.meta,
    };
  }
```

**Expected Behavior**
After execution of subscription operation on Studio ApolloGraphql sandbox, i expect to connect to the socket, and receive messages on the emission of events. But get the error subscribe

**Logs**
```
...
🚀 Query endpoint ready at http://localhost:3008/
🚀 Subscriptions ready at ws://localhost:3008/
Internal error occurred during message handling. Please check your implementation. Error: Subscription field must return Async Iterable. Received: undefined.
    at createSourceEventStream (/***/node_modules/graphql/execution/subscribe.js:165:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async subscribe (/***/node_modules/graphql/execution/subscribe.js:67:26)
    at async onMessage (/***/node_modules/graphql-ws/lib/server.js:191:51)
    at async WebSocket.<anonymous> (/***/node_modules/graphql-ws/lib/use/ws.js:83:21)
```

**Environment (please complete the following information):**

- OS: [e.g. MacOS Monteray]
- Node (e.g. 16.17.0)
- Package version [e.g. 8.15] npm
- TypeScript version (e.g. 4.7.4)

**Additional Context**

**Comment by MichalLytek** [comment]
Please create a PR with a failing test case. I can't guess from your snippets what's wrong with your apollo server, federation or server configuration.

**Comment by carlocorradini** [comment]
@V1os 
Have you added the correct *TypeScript* compiler options as shown in [*TypeGraphQL*'s documentation](https://typegraphql.com/docs/installation.html).
*Due to using the `graphql-subscription` dependency that relies on an `AsyncIterator`, we may also have to provide the esnext.asynciterable to the `lib` option:*
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "lib": ["es2018", "esnext.asynciterable"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**Comment by V1os** [comment]
@carlocorradini hi. Yee, i provided needs options `ts`, but i think that it is some little thing, which is hard to see at first sight.

**Comment by carlocorradini** [comment]
@V1os Can you share the project or a failing example?

**Comment by V1os** [comment]
@carlocorradini 
I think how to do it ...
for now, at most, this is the general view of the server and resolver.
By the way, i builded scheme for federation service

**Comment by carlocorradini** [comment]
@V1os Federation version 1 or version 2?

**Comment by V1os** [comment]
2

**Comment by carlocorradini** [comment]
Found the issue, Federation 2 requires `graphql >= 16` while `TypeGraphQL` requires `graphql < 16`. You can follow `TypeGraphQL v2.0` with support for a newer version of `graphql` in [this pull request](https://github.com/MichalLytek/type-graphql/pull/1331).
If you really want to use `Apollo Federation V2` you must have a separate package with `graphql >= 16` and then import it in your main project with `graphql < 16`. If you don't do something crazy, it works flawlessly. Take a look at my example [here](https://github.com/carlocorradini/reCluster/blob/ee1f263dc68311bcc2ebf02e887b1e97ceddd670/backend/packages/helpers/src/buildFederatedSchema.ts).

**Comment by V1os** [comment]
@carlocorradini tnx bro, i will write about the status.

**Comment by carlocorradini** [comment]
@V1os Can we close this issue? 🥳

**Comment by carlocorradini** [comment]
Did you created a different project with `graphql > = 16` (different `package.json`) and imported in main project with `graphql < 16`

**Comment by carlocorradini** [comment]
Unfortunately, without the code or a minimal example, I can't determine what the cause could be.

**Comment by exaucae** [comment]
I experience a variant of this issue. My error message is: 

> Error: Subscription field must return Async Iterable. Received: null

It happens when there's at least 1h uninterupted connection between client and server
 I reported it in graphql-ws ( https://github.com/enisdenjo/graphql-ws/issues/418 )  but seems more appropriate here?

**Comment by electrovir** [comment]
This error happens to me when my `authChecker` returns `false` for the subscription. I want to hide the error (since it's not an error that an unauthorized subscription is blocked) but can't figure out where to do that...

**Comment by electrovir** [comment]
Workaround for `authChecker` issue:

Instead of returning `false` in the `authCheckers` callback, throw an error directly when auth fails. This prevents the irrelevant subscription error.

**Comment by dev-bhargav7** [comment]
I have my resolvers (and schema) separated by small files. In the case of resolvers, they are javascript files, with a final export default resolvers;, and that's the line I had forgotten.

I'll show the code just in case:

```
import { pubSub, names } from '~/src/config/subscriptions';
import { EzfacilityClientBooking } from '~/src/repositories';

const resolvers = {
  Subscription: {
    clientBookingsChanged: {
      subscribe: () => {
        const asyncIterator = pubSub.asyncIterator([names.CLIENT_BOOKINGS_CHANGED]);

        // Fetch immediately the data from EZ
        const clientBooking = new EzfacilityClientBooking();
        clientBooking.getAll();

        return asyncIterator;
      }
    }
  }
};

export default resolvers;
```

**Comment by MichalLytek** [comment]
@dev-bhargav7 Is this a TypeGraphQL code?

**Comment by ceddybi** [comment]
@MichalLytek subscriptions are broken with graphql-yoga too, https://github.com/ceddybi/graphql-workers-subscriptions/blob/main/example/app/schema.ts

https://github.com/bubblydoo/graphql-workers-subscriptions/issues/5

**Comment by MichalLytek** [comment]
@ceddybi What do you mean by "broken"? I would say it's an issue with your setup. Subscriptions are really simple, it's just an async iterator. The whole transportation stuff is outside the TypeGraphQL's jurisdiction.

**Comment by MichalLytek** [comment]
@ceddybi So please try to reproduce your issue in isolation:
https://github.com/MichalLytek/type-graphql/blob/master/tests/functional/subscriptions.ts#L127

For me your use cases are covered in the test scenarios, so if `graphl-js` can handle that, the issue is not on TypeGraphQL side.
