### ISSUE TITLE
2.0.0-beta.1 esm build and start loadResolversFromGlob.js not supported.

### ISSUE THREAD

**Issue by productdevbook** [MichalLytek/type-graphql#1389]
**Describe the Bug**
pnpm install 
pnpm dev // no problem all working.

**But,**

pnpm start

```shell
> esm-graphql-server@0.0.1 compile
> tsc

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/dist/graphql/resolver/user.resolver.js from /home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js not supported.
Instead change the require of user.resolver.js in /home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js to a dynamic import() which is available in all CommonJS modules.
    at /home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js:12:47
    at Array.map (<anonymous>)
    at loadResolversFromGlob (/home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js:12:31)
    at /home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/utils/buildSchema.js:37:67
    at Array.forEach (<anonymous>)
    at loadResolvers (/home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/utils/buildSchema.js:35:27)
    at buildSchema (/home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/utils/buildSchema.js:10:23)
    at buildTypeDefsAndResolvers (/home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/utils/buildTypeDefsAndResolvers.js:8:56)
    at SchemaGenerator (file:///home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/dist/graphql/schema.js:8:43)
    at file:///home/productdevbook/Documents/GitHub/opensource/esm-graphql-server/dist/index.js:33:22
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

**To Reproduce**
https://github.com/productdevbook/esm-graphql-server

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Node v18.12.1
- Package version 2.0.0-beta.1
- TypeScript version 4.9.3

**Comment by MichalLytek** [comment]
glob resolvers support will be removed in 2.0.0 anyway

**Comment by productdevbook** [comment]
dev mode "Query" working, but

add Mutation, 

```ts

  @Mutation()
  async createLibrary(
    @Ctx() { orm }: MyContext,
  ) {
    return ''
  }
 ```
 
 add
 
 ```shell
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'createLibrary' of 'LibraryResolver' class.
    at findType (/home/productdevbook/Documents/ss/server-micro-library/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/findType.js:19:15)
    at getResolverMetadata (/home/productdevbook/Documents/ss/server-micro-library/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/resolver-metadata.js:10:53)
    at <anonymous> (/home/productdevbook/Documents/ss/server-micro-library/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/decorators/Mutation.js:10:50)
    at __decorateClass (file:///home/productdevbook/Documents/ss/server-micro-library/src/graphql/library/library.resolver.ts:1:374)
    at <anonymous> (/home/productdevbook/Documents/ss/server-micro-library/src/graphql/library/library.resolver.ts:14:9)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
 
 ```

**Comment by MichalLytek** [comment]
`@Mutation(returns => String)`

**Comment by productdevbook** [comment]
```ts
  @Mutation(() => Boolean)
  public async deleteRating(@Ctx() { orm }: MyContext, @Arg('data') data: CreateLibraryInput): Promise<boolean> {
    // const library = await orm.create(Library, {
    //   ...data,
    // })

    return true
  }
```

```shell
/node_modules/.pnpm/type-graphql@2.0.0-beta.1_rq55dqxpbhywxwjvxttjguy4yy/node_modules/type-graphql/dist/helpers/findType.js:19
        throw new errors_1.NoExplicitTypeError(prototype.constructor.name, propertyKey, parameterIndex, argName);
              ^


NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for argument named 'data' of 'deleteRating' of 'LibraryResolver' class.
```

inputs

```ts
import { Library } from 'src/entity/library.entity'
import { Field, InputType } from 'type-graphql'

@InputType()
export class CreateLibraryInput implements Partial<Library> {
  @Field(() => String, { description: 'regex: /^[a-zA-Z0-9_]{3,15}$/' })
  name!: string

  @Field(() => String, { nullable: false })
	description?: string

  @Field(() => String, { nullable: false })
  address!: string

  @Field(() => String, { nullable: false })
  phone!: string

  @Field(() => String)
  openingHours!: string

  @Field(() => String)
  closingHours!: string
}
```

**Comment by MichalLytek** [comment]
Have you read the docs and have proper tsconfig options set?

**Comment by productdevbook** [comment]
yes, https://github.com/productdevbook/esm-graphql-server/blob/main/tsconfig.json

**Comment by MichalLytek** [comment]
https://github.com/esbuild-kit/tsx#does-it-have-any-limitations

**Comment by zacharyclaysmith** [comment]
> glob resolvers support will be removed in 2.0.0 anyway

Does that imply that we'll need to manually add imported resolvers to a resolvers array, or will there be a different recommended approach?

**Comment by MichalLytek** [comment]
@zacharyclaysmith 
You will need to figure out your own solution to transform glob string into an array of resolvers classes.
