### ISSUE TITLE
Towards TypeGraphQL v2.0

### ISSUE THREAD

**Issue by MichalLytek** [MichalLytek/type-graphql#1418]
## TypeGraphQL v2.0

The 2.0 release won't be a rewrite from scratch nor a breaking change in the existing API 👀 

Basically, two main goals of this release are:
1) GraphQL v16 upgrade - this is a peer dependency, so it forces bumping version to a new major release ⚠️ 
2) fixes, features and cleanups that might break compatibility in some edge cases

The 1) is mostly done (#1331) however it might need some attention around examples that might not work properly or still need updating deps (e.g. Apollo Server v4).

About the rest, all is described in the changelog:
https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md#unreleased

We're also working with @carlocorradini on reviving the repo and tools configuration that went out-of-date since the project was born 5 years ago, like TSLint has died and Gulp is not used anymore. See the work on #1400.
This should allow external contributors to work on the codebase, implement other fixes and features.

The current state of the art is published as a beta release - `npm i type-graphql@next`:
https://www.npmjs.com/package/type-graphql/v/2.0.0-beta.1

Stay tuned for more info! 📻 

PS No ETA yet, the beta releases are stable enough to be used by users.

**Comment by MichalLytek** [comment]
Reserved for the TODO-list.

**Comment by carlocorradini** [comment]
Add:
 - Rename default branch to `main`
 - Move the examples' dependencies from root `package.json` to the appropriate `package. json`
 - Automatic release with GitHub Actions when a new tag is pushed to `main` branch

**Comment by carlocorradini** [comment]
@MichalLytek Add `concurrency` in Github Action:
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```

**Comment by carlocorradini** [comment]
@MichalLytek Set `tsconfig` property `removeComments` to `false`. This allows having precious hints (Intellisense) in the released code without checking the docs. Moreover, we need to add comments in the code (or part of the code that are "publicly" visible) via [`TSDoc`](https://tsdoc.org). Note that we already have a TSDoc plugin for ESLint in PR #1400

**Comment by MichalLytek** [comment]
@carlocorradini Comments in the code are not API docs. We would need to write full JSDoc and then show it in the `*d.ts` files for intelisense purposes. See #17 👀

**Comment by carlocorradini** [comment]
Yup, I cannot find the issue from typescript repo where they propose to retain comments in JS :/

**Comment by carlocorradini** [comment]
@MichalLytek 
These have been done in #1400 :
`cancel in-progress CI checks when fresh commits were pushed`
`automatic release with GitHub Actions when a new tag is pushed to main branch`

The only thing missing is the NPM_TOKEN secrets

**Comment by carlocorradini** [comment]
> Yup, I cannot find the issue from typescript repo where they propose to retain comments in JS :/

TypeScript issue: https://github.com/microsoft/TypeScript/issues/14619

**Comment by carlocorradini** [comment]
I think we should add an error or warning message if `@Directive` SDL string contains newline characters.
If SDL contains a newline character the directive is completely and silently ignored.

**Comment by MichalLytek** [comment]
@carlocorradini This should be a separate bug ticket, please create, maybe with test case reproduction

**Comment by carlocorradini** [comment]
@MichalLytek Done. I think it should be an easy fix

**Comment by MichalLytek** [comment]
> The only thing missing is the NPM_TOKEN secret

Added.

**Comment by carlocorradini** [comment]
@MichalLytek Add an example that shows how to use [`graphql-scalars`](https://github.com/Urigo/graphql-scalars)

**Comment by carlocorradini** [comment]
> @MichalLytek Add an example that shows how to use [`graphql-scalars`](https://github.com/Urigo/graphql-scalars)

@MichalLytek Done in #1400

**Comment by carlocorradini** [comment]
@MichalLytek All errors that are thrown at runtime (after schema has been successfully built) should extends GraphQLError and not Error

**Comment by AChangXD** [comment]
Any updates to the ETA?

**Comment by carlocorradini** [comment]
> Any updates to the ETA?

Nope 😅

**Comment by AChangXD** [comment]
Seems like the argument validation messages stopped showing with v2.0, similar to #362. Is it a known bug?

**Comment by john-dodson** [comment]
Field resolvers don't work with Apollo Federation v2. It seems that if you are resolving a field for a type that was resolved by a different subgraph the field resolver function will receive an object that looks like this instead of the Root dataValues themselves: 
```
{
  _changed: {...},
  _options: {...},
  _previousDataValues: {...},
  dataValues: {...},
}
```

I'm currently writing my own decorator to account for this, but it's something that should be addressed, probably in the FieldResolver decorator.

**Comment by qfl1ck32** [comment]
Are there any updates on this? There's no way to use type-graphql with @apollo/server at the moment.

**Comment by shellscape** [comment]
@MichalLytek not being able to use `graphql@16` is starting to become a major blocker. All of the tools based on `graphql` are starting to leverage it and we're finding that many of the updates contain critical features we need to use. `graphql@16` will be 1.5 years old very soon, and `@17` is already in testing.

What can be done to get a release out that supports `graphql@16` given that the update to v2.0 is taking quite a while?

**Comment by shellscape** [comment]
> Moreover, in https://github.com/MichalLytek/type-graphql/pull/1400, all runtime errors now extends GraphQLError and have additional information in extensions field (i.e. validationErrors for ArgumentValidationError)

@carlocorradini I don't see any changes in #1400 around `GraphQLError`. I would also recommend following the guild's lead on that as outlined here: https://the-guild.dev/graphql/yoga-server/docs/features/error-masking. Masking the error is going to be preferable to always throwing GraphQLError as most production systems don't want to bleed internal info to end users. We're using `graphql-yoga` to serve the schema that `typegraphql-prisma` generates, and throwing `GraphQLError` will instruct `graphql-yoga` to allow those errors to be delivered without masking to the end user.

**Comment by carlocorradini** [comment]
@shellscape 
All [these](https://github.com/carlocorradini/type-graphql/tree/maintainability/src/errors/graphql) errors `extends GraphQLError`:
1. `ArgumentValidationError`
   ```ts
   export class ArgumentValidationError extends GraphQLError {
     public constructor(validationErrors: ValidationError[]) {
       super("Argument Validation Error", {
         extensions: {
           code: "BAD_USER_INPUT",
           validationErrors,
         }
       });
     }
   }
   ```

1. `AuthenticationError`
   ```ts
   export class AuthenticationError extends GraphQLError {
     public constructor(
       message = "Access denied! You need to be authenticated to perform this action!",
     ) {
       super(message, { extensions: { code: "UNAUTHENTICATED" } });
     }
   }
   ```

1. `AuthorizationError`
   ```ts
   export class AuthorizationError extends GraphQLError {
     public constructor(
       message = "Access denied! You don't have permission for this action!")
     {
       super(message, { extensions: { code: "UNAUTHORIZED" } });
     }
   }
   ```

All of the above errors do not disclose any sensible information, hence they shouldn't be hidden. If you really want to hide them, just catch the error and return a more generic one.

**Comment by shellscape** [comment]
> All these errors extends GraphQLError

great, those should be fine.

> If you really want to hide them, just catch the error and return a more generic one.

That's reasonable using this lib directly, not so much when using with the sister lib typegraphql-prisma.

**Comment by carlocorradini** [comment]
@shellscape 
This is straightforward.
See https://www.apollographql.com/docs/apollo-server/data/errors as an example.
There is no difference between `typegraphql` and `typegraphql-prisma` since the error handling is done in/by the server and not in the "logic".

**Comment by shellscape** [comment]
I didn't imply that there was, perhaps that's a language barrier issue.

> error handling is done in/by the server and not in the "logic".

While I understand that you have a good grasp on this project, the verbiage here isn't quite correct. For clarity for other readers, Error handling and throwing are done within the _resolvers_ even if that's a wrapped resolver from one of the builtin directives. That doesn't necessarily need to be within a server (if you've not used graphql in actually serverless environments, it's a fun exercise), and it's not done directly by the server. Because errors are thrown in resolvers, for an error like `ArgumentValidationError`, this is problematic with a lib like `typegraphql-prisma` as the default usage is not to isolate all resolvers as separate imports and manually construct the schema from those imports. That falls under advanced and nuanced usage. That said, that error should be fine to bleed through past `graphql-yoga`s error masking.

> See https://www.apollographql.com/docs/apollo-server/data/errors as an example.

That's only tangentially related to what we're discussing, which is a bit beyond beginner level understanding of GraphQL errors. I'd also very much recommend linking to the guild's documentation rather than Apollo, since Apollo tends to be a lot more nuanced towards the products they're shipping, which don't always align with GraphQL to spec. What we're discussing is arguably more advanced. 

> This is straightforward.

This is generally a bad reply to make on github, support, or in open source projects. It assumes the other party comprehends things as you do, and speaks down to them if they do not. I would recommend avoiding that language in the future. I offer this advice after spending ~20 years in open source. Being a maintainer means curbing the urge to be terse and/or direct.

**Comment by MichalLytek** [comment]
Long story short: GraphQL servers are responsible for transforming the runtime error (JS Error instances) into JSON response.
So you can tweak this mechanism to your need easily, no matter if using Apollo or Yoga.
The default behavior is to pass `GraphQLError` to the JSON with all the extensions, and that's what most of the people is asking, to know why their request failed, see the validation errors, etc.

For production and safe usage, you can use `formatError`, do simple `instance of` checks and filter all the fragile data, even returning generic "Internal Server Error" with no stack trace 😉

**Comment by shellscape** [comment]
> For production and safe usage, you can use formatError, do simple instance of checks and filter all the fragile data, even returning generic "Internal Server Error" with no stack trace 😉

Excellent. That aligns well with `graphql-yoga`s `maskError` API.

**Comment by carlocorradini** [comment]
@shellscape 
It's not as simple as I imagined to write a response using the GitHub app (apologize)! 😂
Nevertheless, look at the `maintainability"` branch (https://github.com/carlocorradini/type-graphql/tree/maintainability) and share your suggestions on how it might be improved.
Because we are a community, everyone's opinions matter 😎🥳🤯

**Comment by MichalLytek** [comment]
I guess that we might need a dedicated doc for the migration guide 🤔 
There's quite a big list of `Breaking Change` in changelog.

**Comment by vany0114** [comment]
Hi @MichalLytek I'm wondering if the new version supports Apollo Server v4 and Apollo Federation v2? we currently rely on `type-graphql` to build our API Gateway built on top of Apollo Server v3 and Apollo Federation v1.

**Comment by MichalLytek** [comment]
@vany0114 Yes, you can try latest release:
https://github.com/MichalLytek/type-graphql/releases/tag/v2.0.0-beta.2

**Comment by vany0114** [comment]
> @vany0114 Yes, you can try latest release: https://github.com/MichalLytek/type-graphql/releases/tag/v2.0.0-beta.2

Thanks, we'll give it a try then! 🤞

**Comment by russell-dot-js** [comment]
@MichalLytek FYI your changelog for the fix for #1425 accidentally references #1435

**Comment by fliitor** [comment]
Resolver inheritance seams to be broken
See [this post](https://github.com/MichalLytek/type-graphql/discussions/1455#discussioncomment-6269316)
I also test code from [doc](https://github.com/MichalLytek/type-graphql/blob/v2.0.0-beta.2/docs/inheritance.md#resolver-inheritance). Perhaps need to be updated ?

**Comment by pauloendoh** [comment]
> ## Launch control checklist
> * [x]  automatic release with GitHub Actions when a new tag is pushed to `main` branch @carlocorradini
> * [x]  cancel in-progress CI checks when fresh commits were pushed @carlocorradini
> * [x]  remove resolvers glob path (`resolvers: [__dirname + "/migration/*.ts"],`) @MichalLytek
> * [x]  remove `isAbstract` legacy decorator option @MichalLytek
> * [x]  double build support (CJS and ESModules) @carlocorradini
> * [x]  replace custom scalars with `graphql-scalars` library @MichalLytek
> * [x]  errors thrown at runtime should extend `GraphQLError` and not Error @carlocorradini
> * [x]  enable schema check for `buildSchemaSync` @MichalLytek
> * [x]  making class-validator optional peer dependency @MichalLytek
> * [x]  upgrade to [TypeScript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/) with all the goodness (like `const`) but without new decorators @MichalLytek
> * [ ]  move the examples' dependencies from root `package.json` to the appropriate `package. json` @carlocorradini
> * [ ]  ...

Just for curiosity, why remove glob paths?

**Comment by okaforcj** [comment]
> 

yeah @MichalLytek @pauloendoh please what would be the replacement/alternative for this please, I have over 25 resolvers and it was more efficient to just colocate in the resolver folder and use the matcher to find it there. Is the only solution now to list all of them manually?

**Comment by vany0114** [comment]
Hi @MichalLytek I'm curious if is there a way to inject the following in the schema or `type-graphql` already supports the federation v2 out of the box? 

```
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3",
        import: ["@key", "@shareable"])
```

**Comment by carlocorradini** [comment]
@vany0114 See [this](https://github.com/carlocorradini/type-graphql/tree/maintainability/examples%2Fapollo-federation)

It's currently in my repo but it will be merged soon (see PR #1700)

**Comment by vany0114** [comment]
@carlocorradini Thanks! do you guys have a sense of when it's gonna be released?

**Comment by carlocorradini** [comment]
@vany0114 This week it should be merged.
I don't know the exact date for the release, let's wait @MichalLytek 
:)

**Comment by vany0114** [comment]
@carlocorradini gotcha, in the meantime can you point me to where is that implemented to see if I can borrow it while it is released? 🙏

**Comment by carlocorradini** [comment]
Simply run:
```sh
npm uninstall type-graphql
npm install type-graphql@next
```
Easy peasy 😎

**Comment by vany0114** [comment]
I guess that would install the "unofficial" package and I'd like to avoid it, so if the code that extends the schema is not too complex I'd like to incorporate it on my own `buildFederatedSchema` while your PR is released so that the schema contains this:  and can be considered by Apollo that is using the federation v2.

```
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3",
        import: ["@key", "@shareable"])
```

**Comment by vany0114** [comment]
@MichalLytek not sure if I misunderstood but in [this comment](https://github.com/MichalLytek/type-graphql/pull/1400#issuecomment-1655114489) you say that the extend schema stuff is added automatically by the `buildSubgraphSchema`
> It's added automatically by buildSubgraphSchema - see helpers/buildFederatedSchema

However, I was reviewing the implementation and it seems it's not, also the [documentation says](https://www.apollographql.com/docs/apollo-server/using-federation/apollo-subgraph-setup/#2-opt-in-to-federation-2) it needs to be added in the schema. 

So I'm curious whether the opt-in to Federation 2 is really supported (or it's gonna be) by `type-graphql` 🤔

**Comment by RealSebbooo** [comment]
Hello everyone, i am struggling to use the buildSchema function. Can someone tell me how to convert my glob path strings into resolver classes to use them in the buildSchema function.

**Comment by carlocorradini** [comment]
@RealSebbooo 
Glob paths resolvers option has been removed. See [CHANGELOG.md](https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md)

**Comment by RealSebbooo** [comment]
And what is the alternative so that i can import my resolvers from a different file?

**Comment by MichalLytek** [comment]
@RealSebbooo You should just use imports and resolvers array. Dummy require might produce weird issues and is not supported anymore.

**Comment by MichalLytek** [comment]
@john-landgrave There is a pending refactor/rewrite of the subscriptions support as the old package is not maintained anymore:
https://github.com/MichalLytek/type-graphql/pull/1578

Then I need to make sure all issues requiring breaking changes are implemented, write some migrations docs and we should be ready to launch!

**Comment by MichalLytek** [comment]
The 4th beta release has been published! 🚀 

As you can read in the changelog, it has new features for directives, validation and mostly subscriptions - now it uses the `@graphql-yoga/subscriptions` package, instead of old and abandoned `graphql-subscriptions`.
It accepts any `PubSub` implementation that matches the thin interface, so you can use any other package you want, if the yoga's one does not fulfill your needs 😉 

There's also a migration guide for this major and big breaking change:
https://typegraphql.com/docs/migration-guide.html#subscriptions

Feel free to leave here any feedback about the improved subscriptions support! 🙏

**Comment by john-landgrave** [comment]
@MichalLytek thanks for the update! What version of Prisma will v2 require?

**Comment by MichalLytek** [comment]
@john-landgrave We're on the core TypeGraphQL repo, not the Prisma integration 😉

**Comment by john-landgrave** [comment]
Whoops, you're right! I'll check issues and see if there's any news on that
over there. Thanks!

**Comment by eduardolundgren** [comment]
> It accepts any `PubSub` implementation that matches the thin interface, so you can use any other package you want, if the yoga's one does not fulfill your needs 😉

@MichalLytek, I appreciate the latest update. You mentioned that it should be compatible with any PubSub adhering to the interface. However, I've encountered an issue: when attempting to use RedisPubSub as PubSub, the Apollo client fails to connect. This makes me curious if there might be a bug within the new default Yoga implementation's internal assumptions.

```
Internal error occurred during message handling. Please check your implementation. TypeError: source[Symbol.asyncIterator] is not a function
    at Object.executor (/packages/api/node_modules/.pnpm/@graphql-yoga+subscription@5.0.0/node_modules/@graphql-yoga/subscription/cjs/operator/filter.js:7:54)
    at /packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:453:69
    at new Promise (<anonymous>)
    at execute (/packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:453:19)
    at Repeater.next (/packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:484:13)
    at Object.next (/packages/api/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/mapAsyncIterator.js:43:39)
    at onMessage (/packages/api/node_modules/.pnpm/graphql-ws@5.14.3_graphql@16.8.1/node_modules/graphql-ws/lib/server.js:210:180)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.<anonymous> (/packages/api/node_modules/.pnpm/graphql-ws@5.14.3_graphql@16.8.1/node_modules/graphql-ws/lib/use/ws.js:83:21)
```

**Comment by eduardolundgren** [comment]
> > It accepts any `PubSub` implementation that matches the thin interface, so you can use any other package you want, if the yoga's one does not fulfill your needs 😉
> 
> @MichalLytek, I appreciate the latest update. You mentioned that it should be compatible with any PubSub adhering to the interface. However, I've encountered an issue: when attempting to use RedisPubSub as PubSub, the Apollo client fails to connect. This makes me curious if there might be a bug within the new default Yoga implementation's internal assumptions.
> 
> ```
> Internal error occurred during message handling. Please check your implementation. TypeError: source[Symbol.asyncIterator] is not a function
>     at Object.executor (/packages/api/node_modules/.pnpm/@graphql-yoga+subscription@5.0.0/node_modules/@graphql-yoga/subscription/cjs/operator/filter.js:7:54)
>     at /packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:453:69
>     at new Promise (<anonymous>)
>     at execute (/packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:453:19)
>     at Repeater.next (/packages/api/node_modules/.pnpm/@repeaterjs+repeater@3.0.5/node_modules/@repeaterjs/repeater/cjs/repeater.js:484:13)
>     at Object.next (/packages/api/node_modules/.pnpm/graphql@16.8.1/node_modules/graphql/execution/mapAsyncIterator.js:43:39)
>     at onMessage (/packages/api/node_modules/.pnpm/graphql-ws@5.14.3_graphql@16.8.1/node_modules/graphql-ws/lib/server.js:210:180)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async WebSocket.<anonymous> (/packages/api/node_modules/.pnpm/graphql-ws@5.14.3_graphql@16.8.1/node_modules/graphql-ws/lib/use/ws.js:83:21)
> ```

Did some debugging and this issue does not happen when `topics` is an array. Before I had topics as string.

Unfortunately, it surfaced another issue, the payload is always returning `0` instead of the desired value.

```
@Resolver()
export class SubscriptionResolver {
  @Subscription(() => NewMutationPayload, {
    filter: ({ payload } ) => {
      console.log('payload', payload); // PRINTING 0 <--- NEW ISSUE
      ...
    },
    topics: [SubscriptionTopics.NEW_MUTATION], // <--- FIX
  })
  onCompanyRelatedMutation(@Root() newMutation: NewMutationPayload): NewMutationPayload {
    return newMutation;
  }
}
```

**Comment by MichalLytek** [comment]
> with any PubSub adhering to the interface

Yes, but `graphql-subscriptions` are outdated and not supported out of the box.
I haven't added a snippet or adapter in order to force people to migrate from an abandoned package.

> when attempting to use RedisPubSub as PubSub

There is a redis subscription example on the repo. 
I recommend to read the docs about serializer too 😉 
https://the-guild.dev/graphql/yoga-server/docs/features/subscriptions#custom-serializer

**Comment by eduardolundgren** [comment]
@MichalLytek thanks for the reply, and I will give another shot this week. I noticed that recent examples have transitioned from Apollo Server to Yoga, particularly because of the subscriptions, due to the graphql-subscriptions library being outdated. This shift raises a question: why has Apollo Server been phased out in the examples in favor of Yoga?

Would it be possible to reintroduce an example that combines Apollo Server with some working subscriptions? Such an example would be invaluable for those of us looking to understand how Apollo Server can still be utilized effectively, especially in contexts where its subscription capabilities are essential.

Thank you for considering this request. Your efforts in maintaining and evolving this project are greatly appreciated!

**Comment by MichalLytek** [comment]
@eduardolundgren 
The changes were made in terms of internal PubSub system. It doesn't change at all the way we expose GraphQL schema via http and websockets.
So you just follow the steps defined in the apollo-server docs:
https://www.apollographql.com/docs/apollo-server/data/subscriptions/#enabling-subscriptions

**Comment by eduardolundgren** [comment]
@MichalLytek, you were right. I kept my existing Apollo Server setup as described in the Apollo Server docs and just switched my subscription setup to use @graphql-yoga/subscription and @graphql-yoga/redis-event-target. Everything's working smoothly now. I also updated to 2.0.0-beta.6, so not sure if that also helped — thanks for the help!

**Comment by MichalLytek** [comment]
ℹ️ Quick update regarding 2.0 release ℹ️ 

The goal is to group all the breaking changes, because of major version bump.
It took a while to e.g. rework subscriptions but we're now much closer to the final release! 🚀 

Today I've published the first RC release. It's also marked as the `latest` tag on npm, so it will be the default version which developers install.

Before releasing stable 2.0, I would like to work on those issues and PRs:
https://github.com/MichalLytek/type-graphql/issues/620
https://github.com/MichalLytek/type-graphql/pull/1297
https://github.com/MichalLytek/type-graphql/issues/1453
https://github.com/MichalLytek/type-graphql/issues/1325
https://github.com/MichalLytek/type-graphql/pull/1330

Stay tuned! 📻

**Comment by codingthat** [comment]
@MichalLytek Thanks for the update!  I notice that all the issues and PRs you linked to are now completed or merged (except #1453 marked as invalid, and #1330 superseded by now-merged #1680).  The [milestone](https://github.com/MichalLytek/type-graphql/milestone/8) has nothing open on it either.  Does that mean readme/docs updates are the last blocker?

**Comment by MichalLytek** [comment]
Not 100% sure but looks like so 😉 

We definitely need a good migration guide, which I started writing some time ago.
Then updating docs/readme with a proper, up to date introduction.
Finally we can schedule a 2.0 stable release with some tweets, blog posts, etc. 🎉

**Comment by Kleywalker** [comment]
I love the project und am looking forward to version 2.0 stable! 😊 Are there any updates yet? I would like to start a new project leading with TypeGraphQL 2.0.

BTW: Does this work with Bun runtime? Are the Plans to optimize it for Bun?

Thanks for the great work! 😊

**Comment by jziggas** [comment]
#1806 completes the [2.0 Milestone](https://github.com/MichalLytek/type-graphql/milestone/8)

**Comment by MichalLytek** [comment]
So now we just need AI to write the migration guide and an announcement blog post 🙌

**Comment by jziggas** [comment]
Oh, [fine](https://github.com/MichalLytek/type-graphql/pull/1808).

**Comment by MichalLytek** [comment]
Guys, please test the 2.0.0-rc.4 release, as looks like caching introduced some bugs 😬 
https://github.com/MichalLytek/type-graphql/issues/1810
