### ISSUE TITLE
I cannot import my resolvers from a folder path

### ISSUE THREAD

**Issue by c-semaan** [MichalLytek/type-graphql#1467]
**Describe the Bug**
I cannot import all my resolvers at once using a path to the parent folder which contains all my resolvers.

**To Reproduce**

  
```  

  // this does not work
  const resolversPath = path.join(__dirname, "./resolvers/*.resolver.{ts,js}"); // outputs C:\Users\Charles\Desktop\QC\server\src\resolvers\*.resolver.{ts,js}
  const schema = await buildSchema({
    resolvers: [resolversPath], // produces error using the resolversPath but works when I import the class manually
  });
  
  // this works
  import { UserResolver } from "./resolvers/user.resolver";
   const schema = await buildSchema({
    resolvers: [UserResolver],
  });
```
  

**Expected Behavior**
-
**Logs**
I am getting this error:

```
GeneratingSchemaError: Some errors occurred while generating GraphQL schema:
  Type Query must define one or more fields.
Please check the `details` property of the error to get more detailed info.
    at Function.generateFromMetadata (C:\Users\Charles\Desktop\QC\server\node_modules\type-graphql\dist\schema\schema-generator.js:38:23)
    at buildSchema (C:\Users\Charles\Desktop\QC\server\node_modules\type-graphql\dist\utils\buildSchema.js:10:55)
    at C:\Users\Charles\Desktop\QC\server\src\index.ts:108:35
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Charles\Desktop\QC\server\src\index.ts:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  details: [
    GraphQLError: Type Query must define one or more fields.
        at SchemaValidationContext.reportError (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\type\validate.js:73:7)
        at validateFields (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\type\validate.js:271:13)
        at validateTypes (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\type\validate.js:244:7)
        at validateSchema (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\type\validate.js:43:3)
        at graphqlImpl (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\graphql.js:60:63)
        at graphqlSync (C:\Users\Charles\Desktop\QC\server\node_modules\graphql\graphql.js:33:18)
        at Function.generateFromMetadata (C:\Users\Charles\Desktop\QC\server\node_modules\type-graphql\dist\schema\schema-generator.js:36:58)
        at buildSchema (C:\Users\Charles\Desktop\QC\server\node_modules\type-graphql\dist\utils\buildSchema.js:10:55)
        at C:\Users\Charles\Desktop\QC\server\src\index.ts:108:35
        at Generator.next (<anonymous>) {
      path: undefined,
      locations: undefined,
      extensions: [Object: null prototype] {}
    }
```

**Environment (please complete the following information):**

- OS: Windows
- Node 18
- Package version 2.0.0-beta
- TypeScript version 5.1.6

**Additional Context**
It was working fine before I upgraded typegraphql from 1.1.1 to 2.0.0-beta. I also upgraded apollo server from 2 to 4 not sure if this might be related.

**Comment by MichalLytek** [comment]
Please migrate to `resolvers: [UserResolver],` syntax. Glob path string is removed in 2.0.

**Comment by comp615** [comment]
Reasonable. Would it be possible to get a better / re-thrown error message to note this deprecation? Additionally, is there any sample code available for how one might handle the globbing themselves if they wanted to? Basically simulate what v1 did as a migration path.

**Comment by MichalLytek** [comment]
> Would it be possible to get a better / re-thrown error message to note this deprecation?

This is a beta release for those who read change log.
The final release will have a release blog post with a migration guide, so it will be easy to update your codebase 😉

**Comment by whlsxl** [comment]
Hello @MichalLytek, So how to load resolvers by path?
