### ISSUE TITLE
Base abstract class is referenced/instantiated when child class should be

### ISSUE THREAD

**Issue by comp615** [MichalLytek/type-graphql#1492]
**Describe the Bug**
Assume you have some type of union or polymorphic object as shown in the example. You may want to have an abstract value which can be set by any child/implementation. In many of the examples, this is shown as an abstract class with an `@ObjectType({ implements: BaseClass })` in children.

However, when it comes to actually running the methods, it seems like they are being executed on the BaseClass instead of the ChildClass. This means that concrete base class methods cannot reference or use abstract methods on the base class (since they are not instantiated).

While I haven't spelunked enough to understand exactly what's going on, my hunch is that typegraphql is calling BaseClass.value() instead of ChildClass.value(). This distinction would not matter normally, but comes into play when you truly start using abstraction and inheritance.

**To Reproduce**
https://codesandbox.io/p/sandbox/typegraphql-v2-demo-forked-wkyhwm?file=/src/index.ts:106,33

**Expected Behavior**
The function as shown should work and return the value from the child class

**Logs**
```
          "TypeError: this._publicationDate is not a function",
          "    at BaseItem.publicationDate (/project/sandbox/src/index.ts:30:17)",
          "    at /project/sandbox/node_modules/type-graphql/dist/resolvers/create.js:64:45",
          "    at applyMiddlewares (/project/sandbox/node_modules/type-graphql/dist/resolvers/helpers.js:59:16)",
          "    at /project/sandbox/node_modules/type-graphql/dist/resolvers/create.js:52:47",
          "    at field.resolve (/project/sandbox/node_modules/@apollo/server/src/utils/schemaInstrumentation.ts:82:22)",
          "    at executeField (/project/sandbox/node_modules/graphql/execution/execute.js:492:20)",
          "    at executeFields (/project/sandbox/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/project/sandbox/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/project/sandbox/node_modules/graphql/execution/execute.js:646:12)",
          "    at completeValue (/project/sandbox/node_modules/graphql/execution/execute.js:595:23)"
```

**Environment (please complete the following information):**

- OS: all
- Node 16
- Package version - v2
- TypeScript version - 4.7

**Comment by comp615** [comment]
Appreciate the response. Ok, I updated the example. It was an incomplete demo of that aspect for sure. Thanks for bearing with me as I work through this in my brain. I guess the more general question is...how do we implement an "interface" (both in the graphql sense and TS sense) for a function. Or can we?

It's obvious how this works for values, but because of the restriction in TS on annotating abstract methods, there doesn't seem to be clear guidance on how to define a method field on the base class and then force implementing it in the subtypes. The old style is to make it concrete in the base class, but implement it as `throw new Error('not implemented')`

**Comment by comp615** [comment]
Appreciate the response. Ok, I updated the example. It was an incomplete demo of that aspect for sure. Thanks for bearing with me as I work through this in my brain. We read through the [example on the site](https://typegraphql.com/docs/interfaces.html#resolving-type:~:text=decorators%20on%20abstract%20methods), but I can't seem to get it going.

I updated the sandbox to try a few methods:
https://codesandbox.io/p/sandbox/typegraphql-v2-demo-forked-wkyhwm?file=/src/index.ts:88,5-94,19

As you mentioned, it seems like returning the data as the appropriate class works. However, I wasn't able to get the resolverType method to work. Is that expected? We're trying to migrate a legacy system to TypeGraphQL so trying to figure out patterns and how we might do that.
