### ISSUE TITLE
ArgsType explicite type required

### ISSUE THREAD

**Issue by RomainDECOSTER** [MichalLytek/type-graphql#1631]
**Describe the Bug**
ArgsType generates NoExplicitError

**To Reproduce**
Code used:
```
@ObjectType()
class CoreContractsResponse extends PaginatedResponse(CoreContract) {
}

@ArgsType()
export class GetAllArgs {
  @Field((_type) => Int)
  skip = 0;

  @Field((_type) => Int)
  limit = 10;
}

@Resolver((_of) => CoreContract)
export class CoreContractResolver {
  @Query((_returns) => CoreContractsResponse)
  async coreContracts(
    @Args() { skip, limit }: GetAllArgs,
    @Ctx() ctx: MyContext,
  ): Promise<CoreContractsResponse> {
    const total: number = await ctx.models.Core.Contract.countDocuments();
    const items = await ctx.models.Core.Contract.find().limit(limit).skip(skip).exec();
    return {
      items,
      total,
    };
  }
}
```

**Logs**
Error:
```
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for parameter #0 of 'coreContracts' of 'CoreContractResolver' class.
    at findType (file:///Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/node_modules/.pnpm/type-graphql@2.0.0-beta.6_class-validator@0.14.1_graphql-scalars@1.22.4_graphql@16.8.1/node_modules/type-graphql/build/esm/helpers/findType.js:22:15)
    at getParamInfo (file:///Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/node_modules/.pnpm/type-graphql@2.0.0-beta.6_class-validator@0.14.1_graphql-scalars@1.22.4_graphql@16.8.1/node_modules/type-graphql/build/esm/helpers/params.js:7:38)
    at file:///Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/node_modules/.pnpm/type-graphql@2.0.0-beta.6_class-validator@0.14.1_graphql-scalars@1.22.4_graphql@16.8.1/node_modules/type-graphql/build/esm/decorators/Args.js:9:16
    at file:///Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/src/features/core/contracts/resolvers.ts:1:543
    at __decorateClass (file:///Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/src/features/core/contracts/resolvers.ts:1:374)
    at <anonymous> (/Users/rdecoster/Projects/Parkki/Core/factoriot-api-v2-typescript/src/features/core/contracts/resolvers.ts:38:9)
```

**Environment (please complete the following information):**

- typescript: 5.3.3
- @apolo/server: 4.10.0
- type-graphql: 2.0.0-beta.4

**Comment by MichalLytek** [comment]
Do you have TypeScript reflection system properly set up according to docs? Are you using other bundler/transpiler that does not support reflection/metadata?
