### ISSUE TITLE
Schema Generation fails in 0.17.5

### ISSUE THREAD

**Issue by kunal-relan** [MichalLytek/type-graphql#407]
I recently upgraded to type-graphql 0.17.5 and while generating schema, I get this error.

node:81114) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at types (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/@nestjs/graphql/node_modules/type-graphql/dist/schema/schema-generator.js:64:59)
    at resolveThunk (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/definition.js:383:40)
    at defineTypes (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/definition.js:765:15)
    at GraphQLUnionType.getTypes (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/definition.js:735:26)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:307:23)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/Users/kunalrelan/Documents/Dev/freelance/ekomi/collect-backend/database/node_modules/graphql/type/schema.js:295:12)
(node:81114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:81114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tomasfrancisco** [comment]
In my case I get the following error when passing down the schema to ApolloServer:
```
Error: Value at "schema" must be of type GraphQLSchema
    at Object.addMockFunctionsToSchema (/Users/user/dev/project/node_modules/graphql-tools/src/mock.ts:71:11)
    at ApolloServer.generateSchemaDerivedData (/Users/user/dev/project/apps/gql/node_modules/apollo-server-core/src/ApolloServer.ts:491:7)
    at new ApolloServerBase (/Users/user/dev/project/apps/gql/node_modules/apollo-server-core/src/ApolloServer.ts:361:32)
    at new ApolloServer (/Users/user/dev/project/apps/gql/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
    at Object.<anonymous> (/Users/user/dev/project/apps/gql/src/index.ts:20:26)
```

**Comment by MichalLytek** [comment]
@kunal-relan 
Do you use the new `types: () => [Foo, Bar]` syntax?

**Comment by pereslavtsev** [comment]
> @kunal-relan
> Do you use the new `types: () => [Foo, Bar]` syntax?

I use the new syntax, but I have the same error :(

**Comment by MichalLytek** [comment]
@pereslavtsev 
I need a small reproduction repo as the tests are passing. Looks like you have circular references in your object types and union type.

**Comment by pereslavtsev** [comment]
@MichalLytek Yes, I have the Event type in entities from the 'types' property (Conversation, Message, Contact etc, see [here](https://github.com/MichalLytek/type-graphql/issues/410). Is there way to resolve circular references in this case?

**Comment by MichalLytek** [comment]
Still cannot reproduce:

```ts
import "reflect-metadata";
import { printSchema } from "graphql";
import { createUnionType, ObjectType, Resolver, Query, buildSchema, Field } from "../../src";

@ObjectType()
class A {
  @Field(type => B)
  b: any;

  @Field(type => AB)
  ab: typeof AB;
}

@ObjectType()
class B {
  @Field(type => A)
  a: any;

  @Field(type => AB)
  ab: typeof AB;
}

const AB = createUnionType({
  name: "AB",
  types: () => [A, B],
});

@Resolver()
class TestResolver {
  @Query(returns => AB)
  ab(): typeof AB {
    return null as any;
  }
}

async function main() {
  const schema = await buildSchema({
    resolvers: [TestResolver],
  });
  console.log(printSchema(schema));
}

main();
```

```graphql
type A {
  b: B!
  ab: AB!
}

union AB = A | B

type B {
  a: A!
  ab: AB!
}

type Query {
  ab: AB!
}
```

**Comment by MichalLytek** [comment]
Still cannot reproduce:

```ts
import "reflect-metadata";
import { printSchema } from "graphql";
import { createUnionType, ObjectType, Resolver, Query, buildSchema, Field } from "../../src";

@ObjectType()
class A {
  @Field(type => B)
  b: any;

  @Field(type => AB)
  ab: typeof AB;
}

@ObjectType()
class B {
  @Field(type => A)
  a: any;

  @Field(type => AB)
  ab: typeof AB;
}

const AB = createUnionType({
  name: "AB",
  types: () => [A, B],
});

@Resolver()
class TestResolver {
  @Query(returns => AB)
  ab(): typeof AB {
    return null as any;
  }
}

async function main() {
  const schema = await buildSchema({
    resolvers: [TestResolver],
  });
  console.log(printSchema(schema));
}

main();
```

```graphql
type A {
  b: B!
  ab: AB!
}

union AB = A | B

type B {
  a: A!
  ab: AB!
}

type Query {
  ab: AB!
}
```

**Comment by pereslavtsev** [comment]
in my case:
```
export const EventDataUnion = createUnionType({
  name: 'EventData',
  types: () => [], // any entities
});


@ObjectType()
export class Event {
  @Field(type => ID)
  id: number;

  @Field(type => EventDataUnion)
  data: typeof EventDataUnion;
}

@Resolver(of => Event)
export class EventsResolver {
  @ResolveProperty(returns => EventDataUnion)
  async data(@Parent() event: Event): Promise<any> {
// some actions
  }
}
```

**Comment by MichalLytek** [comment]
> types: () => [], // any entities

This isn't a reproducible code example. I need a snippet like mine that I can run and see the errors.

**Comment by pereslavtsev** [comment]
@MichalLytek 

try this
```js

@ObjectType()
export class Contact {
  @Field(type => ID)
  id: number;

  @Field(type => Event)
  event: Event;
}

export const EventDataUnion = createUnionType({
  name: 'EventData',
  types: () => [Contact], // any entities
});


@ObjectType()
export class Event {
  @Field(type => ID)
  id: number;

  @Field(type => EventDataUnion)
  data: typeof EventDataUnion;
}

@Resolver(of => Event)
export class EventsResolver {
  @ResolveProperty(returns => EventDataUnion)
  async data(@Parent() event: Event): Promise<any> {
// some actions
  }
}
````

**Comment by MichalLytek** [comment]
```
GraphQLError: Type Query must define one or more fields.
```
Still not runnable example. Do you just blindy paste some snippets from your project's code?

I've updated your code example:
```ts
@ObjectType()
export class Contact {
  @Field(type => ID)
  id: number;

  @Field(type => Event)
  event: any;
}

export const EventDataUnion = createUnionType({
  name: "EventData",
  types: () => [Contact], // any entities
});

@ObjectType()
export class Event {
  @Field(type => ID)
  id: number;

  @Field(type => EventDataUnion)
  data: typeof EventDataUnion;
}

@Resolver(of => Event)
export class EventsResolver {
  @Query()
  test(): string {
    return "test";
  }

  @FieldResolver(returns => EventDataUnion)
  async data(@Root() event: Event): Promise<any> {
    // some actions
  }
}

async function main() {
  const schema = await buildSchema({
    resolvers: [EventsResolver],
  });
  console.log(printSchema(schema));
}

main().catch(console.error);
```

Still cannot reproduce. As you use Nest, you should ask for help in theirs repo, as I'm not responsible for theirs integration that is sometimes faulty:
https://github.com/nestjs/graphql/issues/231

**Comment by pereslavtsev** [comment]
@MichalLytek 
thanks, I will ask in their repo

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

Feel free to reopen this issue if the problem still happens in `v0.18.0-beta.1`.

**Comment by ashkart** [comment]
I have got error like that when working with union result type.
Here is [working demo](https://codesandbox.io/s/github/ashkart/typegraphql_issue_demo)
Uncomment `getUserWithUnion` method in `resolver.ts` to reproduce the preoblem.

```

TypeError: Cannot read property 'type' of undefined
    at /home/maxim/workspace/demo/node_modules/type-graphql/dist/schema/schema-generator.js:66:101
    at Array.map (<anonymous>)
    at types (/home/maxim/workspace/demo/node_modules/type-graphql/dist/schema/schema-generator.js:66:22)
    at resolveThunk (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:438:40)
    at defineTypes (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:837:15)
    at GraphQLUnionType.getTypes (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:806:26)
    at typeMapReducer (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:272:28)
    at typeMapReducer (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:145:28)

```
