### ISSUE TITLE
TypeORM @CreateDateColumn and @UpdateDateColumn throws Error with Apollo-Server

### ISSUE THREAD

**Issue by evanzulli** [MichalLytek/type-graphql#428]
I have two related entities, wich make use of the @CreateDateColumn and @UpdateDateColumn decorators.

Marca.ts
```
@ObjectType()
@Entity()
export class Marca
{
    @Field( type => ID )
    @PrimaryGeneratedColumn()
    id: number

    @Field()
    @Column()
    nombre: string

    @Field()
    @CreateDateColumn()
    fechaCreacion: Date

    @Field()
    @UpdateDateColumn()
    fechaModificacion: Date
 
   @Field( type => [Modelo] )
    @OneToMany( type => Modelo, modelo => modelo.marca )
    modelos: Modelo[]
}
```

Modelo.ts
```
@ObjectType()
@Entity()
export class Modelo
{
    @Field( type => ID )
    @PrimaryGeneratedColumn()
    id: number

    @Field()
    @Column()
    nombre: string

    @Field()
    @CreateDateColumn()
    fechaCreacion: Date

    @Field()
    @UpdateDateColumn()
    fechaModificacion: Date

    @Field( type => Marca )
    @ManyToOne( type => Marca, marca => marca.modelos )
    marca: Marca
}
```

If I do comment out the @Decorated columns, Apollo Server thru TypeGraphQL works fine. But if I do use theese Entities as before I get theese Errors:

GraphQL
```
{
  modelos {
    id
    nombre
    marca
    {
      id
    }
  }
}
```

Error
```
{
  "errors": [
    {
      "message": "Cannot destructure property `marca` of 'undefined' or 'null'.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "modelos",
        0,
        "marca"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot destructure property `marca` of 'undefined' or 'null'.",
            "    at CelularModeloResolver.<anonymous> (...\\Modelo.ts:32:3)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (...\\Modelo.ts:16:58)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

And on the other side of the relation

GraphQL
```
{
  marcas {
    id
    nombre
    modelos
    {
      id
    }
  }
}
```
Error
```
{
  "errors": [
    {
      "message": "Cannot destructure property `modelos` of 'undefined' or 'null'.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "marcas",
        0,
        "modelos"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot destructure property `modelos` of 'undefined' or 'null'.",
            "    at CelularMarcaResolver.<anonymous> (...\\Marca.ts:32:3)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (...\\Marca.ts:16:58)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
What am I doing wrong? Or is it a bug? Plese help. 
Thanks a lot!

**Comment by Vontus** [comment]
Can you include your resolver code? The entities look fine.

**Comment by MichalLytek** [comment]
You have to implement field resolvers for fetching the relations entities. Just like in examples:
https://github.com/MichalLytek/type-graphql/blob/v0.17.5/examples/typeorm-basic-usage/resolvers/recipe-resolver.ts

**Comment by evanzulli** [comment]
I did not explicitly resolve thoose fields since they are Date fields and other Date fields resolve transparently.

Anyhow I leave you the code of the Resolvers

MarcaResolver
```
import { Resolver, FieldResolver, Root, Query, Arg, Int } from "type-graphql";
import { Repository }       from "typeorm";
import { InjectRepository } from "typeorm-typedi-extensions";

import { Marca }     from "../entity/Marca";
import { Modelo }    from "../entity/Modelo";

@Resolver(of => Marca)
export class MarcaResolver 
{
  constructor
  ( 
    @InjectRepository( Marca ) 
    private readonly marcasRepo: Repository<Marca> 
  ) {}
  
  @Query(returns => Marca, { nullable: true })
  async marca( @Arg("id", type => Int) id: number)
  {
    return await this.marcasRepo.findOne(id);
  }
  @Query(returns => [Marca])
  async marcas(): Promise<Marca[]> 
  {
    return await this.marcasRepo.find();
  }  
  @FieldResolver()
  async modelos( @Root() marca: Marca ) : Promise<Modelo[]>
  {
    const { modelos } = ( await this.marcasRepo.findOne( marca, { relations: ["modelos"] } ) )
    return modelos!
  }
} 
```
ModeloResolver
```
import { Resolver, FieldResolver, Root, Query, Arg, Int } from "type-graphql";
import { Repository } from "typeorm";
import { InjectRepository } from "typeorm-typedi-extensions";

import { Marca } from "../entity/Marca";
import { Modelo } from "../entity/Modelo";

@Resolver(of => Modelo)
export class ModeloResolver 
{
  constructor
  ( 
    @InjectRepository( Modelo ) 
    private readonly modelosRepo: Repository<Modelo>,
  ) {}
  
  @Query(returns => Modelo, { nullable: true })
  async modelo( @Arg("id", type => Int) id: number)
  {
    return await this.modelosRepo.findOne( id )
  }
  @Query(returns => [Modelo])
  async modelos(): Promise<Modelo[]> 
  {
    return await this.modelosRepo.find()
  }  
  @FieldResolver()
  async marca( @Root() modelo: Modelo ) : Promise<Marca>
  {
    const { marca } = await this.modelosRepo.findOne( modelo, { relations: ["marca"] })
    return marca!
  }
}
```
Thanks a lot.

**Comment by MichalLytek** [comment]
> I did not explicitly resolve thoose fields since they are Date fields and other Date fields resolve transparently.

Your example query tells that you fetch the relations:
```graphql
{
  marcas {
    id
    nombre
    modelos
    {
      id
    }
  }
}
```
As well as the error `Cannot destructure property `modelos` of 'undefined' or 'null'.`

**Comment by evanzulli** [comment]
https://github.com/evanzulli/ecellusis/invitations

Just moved in...

**Comment by MichalLytek** [comment]
It's not  a minimal reproducible code example (no relation, just a single plain entity, sqlite database, etc.) - I can't debug your whole app with 10+ entities.

Create a simple reproducible example for `@CreateDateColumn()`.

**Comment by evanzulli** [comment]
I finally got to the mess. I guess i did it wrong, but without DateColumns it worked fine. I had to change the first parameter of the findOne() method from Entity object to a number with the ID of this Entity.

This fails (with DateColumns)
```
  @FieldResolver()
  async marca( @Root() modelo: CelularModelo ) : Promise<CelularMarca>
  {
    const { marca } = await this.modelosRepo.findOne( modelo, { relations: ["marca"] });
    return marca;
  }
```
With this error logged out to the console
`(node:15704) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

This runs fine (with DateColumns)
```
 @FieldResolver()
  async marca( @Root() modelo: CelularModelo ) : Promise<CelularMarca>
  {
    const { marca } = await this.modelosRepo.findOne( modelo.id, { relations: ["marca"] });
    return marca;
  }
```
Is this so meant to be?
Thanks

**Comment by MichalLytek** [comment]
Yes, find one is for looking by id or by `{ where }` - looks like your query failed because of some problems with `Date` serialization.
