### ISSUE TITLE
@UseMiddleware( ), Middleware; first argument is undefined

### ISSUE THREAD

**Issue by tajpouria** [MichalLytek/type-graphql#433]
[ Ubuntu 18.6, node 10.16.3] : I'm just tried to implement basic middleware provided on type-graphql [docs](https://typegraphql.ml/docs/middlewares.html) , but I'm keep receiving following error, is it a problem around my code or a bug withing mentioned library?

http://localhost:4000/graphql
```graphql
# QUERY
query Hello {
  hello
}

# RESPONSE : 
{
  "errors": [
    {
      "message": "Cannot read property 'info' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'info' of undefined",
            "    at new exports.ResolveTime (/home/tajpouria/.pro/fun/TypeGraphql-Series/src/modules/user/middleware/logger.ts:3:51)",
            "    at DefaultContainer.get (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/utils/container.js:15:51)",
            "    at IOCContainer.getInstance (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/utils/container.js:36:42)",
            "    at /home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:67:67",
            "    at Generator.next (<anonymous>)",
            "    at /home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/tslib/tslib.js:110:75",
            "    at new Promise (<anonymous>)",
            "    at Object.__awaiter (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/tslib/tslib.js:106:16)",
            "    at dispatchHandler (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:54:28)",
            "    at Object.<anonymous> (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:82:16)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

./modules/user/middleware/ResolveTime.ts
```typescript
import { MiddlewareFn } from "type-graphql";

export const ResolveTime: MiddlewareFn = async ({ info }, next) => {
    const start = Date.now();
    await next();
    const resolveTime = Date.now() - start;
    console.log(
        `${info.parentType.name}.${info.fieldName} [${resolveTime} ms]`
    );
};
```
./modules/user/middleware/UserResover.ts

```typescript
import { Resolver, Query, Mutation, Arg, UseMiddleware } from "type-graphql";
import { User } from "../../entity/User";
import { RegisterInput } from "./register/RegisterInput";

import { ResolveTime } from "./middleware/ResolveTime";

@Resolver()
export class UserResolver {
    @Query(() => String)
    @UseMiddleware(ResolveTime)
    hello(): string {
        return "hello user";
    }

    @Query(() => [User])
    async users(): Promise<User[]> {
        const users = await User.find();

        return users;
    }

    @Mutation(() => User)
    async register(@Arg("input")
    {
        firstName,
        lastName,
        email,
        password
    }: RegisterInput): Promise<User> {
        const user = await User.create({
            firstName,
            lastName,
            email,
            password
        }).save();

        return user;
    }
}
```
./index.ts

```typescript
import "reflect-metadata";
import express from "express";
import { ApolloServer } from "apollo-server-express";
import { buildSchema } from "type-graphql";
import { createConnection } from "typeorm";
import cors from "cors";
import session from "express-session";
import connectRedis from "connect-redis";

import { UserResolver } from "./modules/user/UserResolver";
import { redis } from "./redis";
import { LoginResolver } from "./modules/user/LoginResolver";
import { MeResolver } from "./modules/user/MeResolver";

const RedisStore = connectRedis(session);

(async () => {
    const app = express();

    app.use(cors({ credentials: true, origin: "http:// localhost:3000" }));

    app.use(
        session({
            store: new RedisStore({ client: redis as any }),
            name: "qid",
            secret: "cat keyboard",
            resave: false,
            saveUninitialized: false,
            cookie: {
                httpOnly: true,
                secure: process.env.NODE_ENV === "production",
                maxAge: 1000 * 60 * 60 * 24 * 7 * 365 // 7 year
            }
        })
    );

    await createConnection();

    const schema = await buildSchema({
        resolvers: [UserResolver, LoginResolver, MeResolver]
    });

    const apolloServer = new ApolloServer({
        schema,
        context: ({ req }) => ({ req })
    });

    apolloServer.applyMiddleware({ app });

    app.listen(4000, () => {
        console.log("Listening on port 4000...");
    });
})();

```

package.json
```json
{
    "name": "TypeGraphql-Series",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "dependencies": {
        "apollo-server-express": "^2.9.4",
        "bcryptjs": "^2.4.3",
        "class-validator": "^0.10.1",
        "connect-redis": "^4.0.2",
        "cors": "^2.8.5",
        "express": "^4.17.1",
        "express-session": "^1.16.2",
        "graphql": "^14.5.8",
        "ioredis": "^4.14.1",
        "pg": "^7.12.1",
        "reflect-metadata": "^0.1.13",
        "type-graphql": "^0.17.5",
        "typeorm": "^0.2.19",
        "typescript": "^3.6.3"
    },
    "devDependencies": {
        "@types/bcryptjs": "^2.4.2",
        "@types/connect-redis": "^0.0.11",
        "@types/cors": "^2.8.6",
        "@types/express": "^4.17.1",
        "@types/express-session": "^1.15.14",
        "@types/ioredis": "^4.0.18",
        "@types/node": "^12.7.8",
        "ts-node-dev": "^1.0.0-pre.43"
    },
    "scripts": {
        "start": "tsnd --respawn  src/index.ts"
    }
}

```

**Comment by MichalLytek** [comment]
Looks like a wrong TypeScript compilation target, so the arrow function is treated like a constructor function so it tries to create an instance of the class using the DI container.

**Comment by tajpouria** [comment]
Changing "target" field on tsconfig file from "es5" to "es6" solved my problem:
./tsconfig.json
```json
    "target": "es6", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
```
I'm also noticed when I'm using function keyword to decleare Middlware(.e.g.ResolveTime.ts ) I'll recive pretty much the same error.
```graphql
"errors": [
    {
      "message": "Cannot destructure property `info` of 'undefined' or 'null'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot destructure property `info` of 'undefined' or 'null'.",
            "    at new exports.ResolveTime (/home/tajpouria/.pro/fun/TypeGraphql-Series/src/modules/middleware/ResolveTime.ts:3:42)",
            "    at DefaultContainer.get (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/utils/container.js:15:51)",
            "    at IOCContainer.getInstance (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/utils/container.js:36:42)",
            "    at /home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:67:67",
            "    at Generator.next (<anonymous>)",
            "    at /home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/tslib/tslib.js:110:75",
            "    at new Promise (<anonymous>)",
            "    at Object.__awaiter (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/tslib/tslib.js:106:16)",
            "    at dispatchHandler (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:54:28)",
            "    at Object.<anonymous> (/home/tajpouria/.pro/fun/TypeGraphql-Series/node_modules/type-graphql/dist/resolvers/helpers.js:82:16)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
