### ISSUE TITLE
Cannot determine Enum Output Type

### ISSUE THREAD

**Issue by Balgorn** [MichalLytek/type-graphql#444]
**Describe the bug**
Using Type-Graphql for a while now, but since yesterday I cannot use additional enum types anymore. I can confirm via logging that the registerEnumtype function is being called, but it appears the type is not available in MetaDataStorage when checking in schema-generator.

**To Reproduce**
This is how my code currently looks (I already deleted all other occurrences of the type to be sure I don't want to override it)

```
export enum abc {
  IMAGE = 'image',
}

registerEnumType(abc, {
  name: 'abc',
});

@ObjectType()
export class PlatformInstagramPostMedia extends AbstractEntity {
  @Field(() => abc)
  test: abc;

  @Field(() => String)
  postInternalId: string;

  @Field(() => String)
  originId: string;

  @Field(() => String)
  mediaURL: string;
}
```

**Expected behavior**
Schema can be generated and the enum is available in schema.

**Logs**
Error reads:
```
(node:23997) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for test
    at Function.getGraphQLOutputType (project/node_modules/type-graphql/dist/schema/schema-generator.js:394:19)
    at objectType.fields.reduce (project/node_modules/type-graphql/dist/schema/schema-generator.js:174:44)
    at Array.reduce (<anonymous>)
    at fields (project/node_modules/type-graphql/dist/schema/schema-generator.js:168:56)
    at resolveThunk (project/node_modules/graphql/type/definition.js:381:40)
    at defineFieldMap (project/node_modules/graphql/type/definition.js:563:18)
    at GraphQLObjectType.getFields (project/node_modules/graphql/type/definition.js:518:27)
    at typeMapReducer (project/node_modules/graphql/type/schema.js:320:61)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (project/node_modules/graphql/type/schema.js:145:28)
(node:23997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Enviorment (please complete the following information):**
 - OS: MacOs
 - Node (e.g. 11.1.0)
 - Package version [e.g. 0.17.5]
 - TypeScript version (e.g. 3.5.1)

**Comment by MichalLytek** [comment]
Please create a minimal reproducible code example repository because it might be a problem with your setup, deps or other config.

**Comment by Balgorn** [comment]
ok I found the issue after looking thoroughly. It appears I am using type-cfg as well, which by coincidence has also a function called registerEnumType with same parameters. 

So long story short -> wrong imported method -> in enum not being registered -> crashes in schema
