### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: You need to provide explicit type for BaseResolver#create parameter #0 !

### ISSUE THREAD

**Issue by redchili-source** [MichalLytek/type-graphql#451]
**Describe the bug**
When I want to create a baseResolver , I hava encountered this error.

```
node:25740) UnhandledPromiseRejectionWarning: Error: You need to provide explicit type for BaseResolver#create parameter #0 !
    at Object.findType (/Users/ben/Documents/w/code/myproject/one_day/server/node_modules/type-graphql/dist/helpers/findType.js:17:15)
    at Object.getParamInfo (/Users/ben/Documents/w/code/myproject/one_day/server/node_modules/type-graphql/dist/helpers/params.js:9:49)
    at /Users/ben/Documents/w/code/myproject/one_day/server/node_modules/type-graphql/dist/decorators/Arg.js:9:159
    at /Users/ben/Documents/w/code/myproject/one_day/server/src/helper/base_resolver.ts:12:37
```

**To Reproduce**
A quick guide how to reproduce the bug.
You can paste here code snippets or even better, provide a link to the repository with minimal reproducible code example.

This is my code.

1. base_resolver.ts
```typescript
import { Resolver, Arg, Mutation } from 'type-graphql'
import { BaseEntity } from 'typeorm';

export default function createBaseResolver<T extends typeof BaseEntity, U>(suffix: string, Entity: T) {
    @Resolver({ isAbstract: true })
    abstract class BaseResolver {
      protected items: T[] = [];
  
      @Mutation(() => Entity, { name: `create${suffix}`})
      async create(@Arg("data") data: U){
        const entity = await Entity.create(data).save();
        return entity;
      }
    }
  
    return BaseResolver;
  }
```

2. ./resolver/plan.ts

```typescript
import { Resolver } from 'type-graphql'
import createBaseResolver from '../helper/base_resolver'
import Plan from '../entity/plan'
import { CreatePlanInput } from '../type/plan'

const PlanBaseResolver = createBaseResolver<typeof Plan, CreatePlanInput>(
    'Plan',
    Plan,
)

@Resolver(() => Plan)
export class PlanResolver extends PlanBaseResolver {}
```

**Expected behavior**

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Enviorment (please complete the following information):**
 - OS: 
 - Node ( 13.0.1)
 - Package version [0.17.5] 
 - TypeScript version (3.6.2)

**Additional context**

**Comment by MichalLytek** [comment]
> `@Arg("data") data: U`

What is the `U` in runtime? `CreatePlanInput`? Is it a class or just an interface?

**Comment by redchili-source** [comment]
Yes ,`U` is the `CreatePlanInput` , and `CreatePlanInput` is a class . That is the code ,
```ts
import { InputType, Field } from 'type-graphql';

@InputType()
export class CreatePlanInput {
    @Field()
    title: string;

}
```

**Comment by MichalLytek** [comment]
So you have to pass that as an argument too, the same way as the `Entity`:
```ts
  export default function createBaseResolver<
    TEntity extends typeof BaseEntity,
    TArgs
  >(suffix: string, Entity: TEntity, EntityArgs: TArgs) {
    @Resolver({ isAbstract: true })
    abstract class BaseResolver {
      protected items: T[] = [];
  
      @Mutation(() => Entity, { name: `create${suffix}`})
      async create(@Arg("data", type => EntityArgs) data: TArgs){
        const entity = await Entity.create(data).save();
        return entity;
      }
    }
  
    return BaseResolver;
  }
```

```ts
const PlanBaseResolver = createBaseResolver(
  'Plan',
  Plan,
  CreatePlanInput,
);
```

**Comment by redchili-source** [comment]
I am tring to add a type for argument , but this code returns a type error.

```
No overload matches this call.
  Overload 1 of 2, '(name: string, options?: Options | undefined): ParameterDecorator', gave the following error.
    Value of type '() => TArgs' has no properties in common with type 'Options'. Did you mean to call it?
  Overload 2 of 2, '(name: string, returnTypeFunc: ReturnTypeFunc, options?: Options | undefined): ParameterDecorator', gave the following error.
    Type 'TArgs' is not assignable to type 'ReturnTypeFuncValue'.
      Type 'TArgs' is not assignable to type 'RecursiveArray<TypeValue>'.ts(2769)
base_resolver.ts(11, 35): Did you mean to call this expression?
types.d.ts(10, 38): The expected type comes from the return type of this signature.
```

**Comment by redchili-source** [comment]
![](http://static.ohcat.xyz/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-10-29%20%E4%B8%8B%E5%8D%889.04.37.png)

**Comment by MichalLytek** [comment]
You have to play a bit with `ClassType` because the type value would be the instance side of the class.

**Comment by redchili-source** [comment]
I fixed this bug , I play a bit with `DeepPartial<BaseEntity>`  because the  `returnTypeFunc: ReturnTypeFunc,` need it .

**Comment by redchili-source** [comment]
```ts
import { Resolver, Arg, Mutation } from 'type-graphql'
import { BaseEntity, DeepPartial } from 'typeorm'

export default function createBaseResolver<
    TEntity extends typeof BaseEntity,
    TArgs extends DeepPartial<BaseEntity>
>(suffix: string, Entity: TEntity, EntityArgs: TArgs) {
    @Resolver({ isAbstract: true })
    abstract class BaseResolver {
        @Mutation(() => Entity, { name: `create${suffix}` })
        async create(@Arg('data', () => EntityArgs) data: TArgs) {
            const entity = await Entity.create(data).save()
            return entity
        }
    }

    return BaseResolver
}
```

**Comment by MichalLytek** [comment]
Ok, so closing this one as it's solved 🔒

**Comment by redchili-source** [comment]
OK，Thank you for answering my doubts ,
