### ISSUE TITLE
Build schema using typescript module resolution

### ISSUE THREAD

**Issue by tiagocorreiaalmeida** [MichalLytek/type-graphql#505]
**Describe the bug**
Im trying to build a schema, im doing so by pointing to a certain path where all the resolvers are located at, this was working perfectly yesterday until decided to use typescript module resolution, now when I try to build the schema it throws an error

**To Reproduce**
Here's the function I call to generate the schema
```javascript
import path from 'path';
import { buildSchema } from 'type-graphql';
import { GraphQLSchema } from 'graphql';

const createSchema = async (): Promise<GraphQLSchema> => {
  try {
    const resolversPath = path.resolve(process.cwd(), 'src/modules/**/resolvers/**/*.ts');
    return await buildSchema({
      resolvers: [resolversPath],
    });
  } catch (e) {
    throw new Error(`Unable to create Graphlql Schema, e: ${e.message}`);
  }
};

export default createSchema;
```

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "ES6",
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "rootDir": "./src",
    "outDir": "./dist",
    "lib": ["ES2016", "ESNext.AsyncIterable"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "paths": {
      "#Modules/*": ["./modules/*"],
      "#Utils/*": ["./utils/*"],
      "#Base/*": ["./*"]
    }
  }
}
```

**Expected behavior**
The file should be generated using  the module resolution from typescript.

**Logs**
The output im getting on the console is the following:
```
Using ts-node version 8.5.4, typescript version 3.7.3
(node:349) UnhandledPromiseRejectionWarning: Error: Unable to create Graphlql Schema, e: Cannot find module '#Modules/user/models'
Require stack:
- /usr/src/app/src/modules/user/resolvers/mutations/register.ts
- /usr/src/app/node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js
- /usr/src/app/node_modules/type-graphql/dist/utils/buildSchema.js
- /usr/src/app/node_modules/type-graphql/dist/utils/index.js
- /usr/src/app/node_modules/type-graphql/dist/index.js
- /usr/src/app/src/config/createSchema.ts
- /usr/src/app/src/index.ts
    at /usr/src/app/src/config/createSchema.ts:12:11
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/src/config/createSchema.ts:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Enviorment (please complete the following information):**
 - OS: alpine
 - Node 13.3.0
 - type-graphql 0.17.5
 - TypeScript 3.7.3

**Comment by MichalLytek** [comment]
Why do you think that is a TypeGraphQL issue when the error comes from your code?

Looks like you don't provide runtime path mapping resolution for TS paths config.

**Comment by tiagocorreiaalmeida** [comment]
@MichalLytek im so sorry, Im new to typescript, I readed a bit around but I dont remember finding info about it on the typescript docs and maybe I had no knowledge of what topic I should search to be honest, I already solved the issue, based on the information you pointed torwards to, sorry for taking your time and thanks for the awesome package :sunglasses:
