### ISSUE TITLE
@Arg not recognized in resolver

### ISSUE THREAD

**Issue by MikyStar** [MichalLytek/type-graphql#530]
**Describe the bug**

It seems like the @Arg annotation doesn't work in my resolver => https://github.com/MikyStar/IDLE/blob/typegraphql/server/src/graphql/User.ts line 56

**To Reproduce**

Just clone my repository https://github.com/MikyStar/IDLE, cd server && npm i && npm start

**Expected behavior**

Being able to use arguments in my mutations and querries

**Logs**

[...]/IDLE/server/lib/graphql/User.js:135
  async login(@(0, _typeGraphql.Arg)("token")
              ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mike/Documents/depots/IDLE/server/lib/index.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)

**Enviorment (please complete the following information):**

 - OS: macOS
 - Node : v12.12.0
 - Package version : npm v6.12.0
 - TypeScript version : ^3.7.3

**Comment by MichalLytek** [comment]
https://github.com/MichalLytek/type-graphql/issues/55#issuecomment-391054109

Closing as duplicate 🔒
