### ISSUE TITLE
Enums are not generating

### ISSUE THREAD

**Issue by mounikakella** [MichalLytek/type-graphql#556]
**Enums are not generating.**

Schema.prisma:
![Screenshot from 2020-03-02 09-08-52](https://user-images.githubusercontent.com/45024975/75643603-891c3180-5c65-11ea-8591-b93e60a2be63.png)
generated file: /generated/type-graphql/enums/PostKind.ts:
![Screenshot from 2020-03-02 09-08-22](https://user-images.githubusercontent.com/45024975/75643608-8a4d5e80-5c65-11ea-9406-76a92c68a622.png)

**To Reproduce**
Define an Enum in `schema.prisma` and run `prisma2 generate`

**Expected behavior**
export enum  should not be empty

**Logs**
```
 GeneratingSchemaError: Generating schema error
    at Function.<anonymous> (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/type-graphql/0.18.0-beta.6_graphql@14.6.0/node_modules/type-graphql/dist/schema/schema-generator.js:21:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/tslib/1.11.0/node_modules/tslib/tslib.js:110:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  details: [
    GraphQLError: Enum type SUBSCRIPTION_STATUS must define one or more values.
        at SchemaValidationContext.reportError (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/type/validate.js:90:19)
        at validateEnumValues (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/type/validate.js:413:13)
        at validateTypes (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/type/validate.js:237:7)
        at validateSchema (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/type/validate.js:54:3)
        at graphqlImpl (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/graphql.js:79:62)
        at /home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/graphql.js:28:59
        at new Promise (<anonymous>)
        at Object.graphql (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/graphql/14.6.0/node_modules/graphql/graphql.js:26:10)
        at Function.<anonymous> (/home/username/projects/project-name/backend/node_modules/.pnpm/registry.npmjs.org/type-graphql/0.18.0-beta.6_graphql@14.6.0/node_modules/type-graphql/dist/schema/schema-generator.js:19:52)
        at Generator.next (<anonymous>) {
      message: 'Enum type PostKind must define one or more values.'
    },
```

**Enviorment (please complete the following information):**
 - OS: ubuntu
 - Node: 12.13.1
 - Package version: 0.1.5
 - TypeScript version: 3.7.4

**Comment by MichalLytek** [comment]
> Any feedback about the developers experience, bug reports or ideas about new features or enhancements are very welcome. However, during the preview I would ask to add comments only in this issue, not to create a new issues, as I don't want to pollute the repo for now 😉

Please move your report to #476 🔒

**Comment by MichalLytek** [comment]
@mounikakella if you still fighting with this issue, it's probably caused by wrong `prisma2` versions - sometimes `typegraphql-prisma` releases has to work with `@alpha` version of `prisma2`. Please check the `package.json` for more info.
