### ISSUE TITLE
Error: TypeError: Cannot read property 'mkdir' of undefined

### ISSUE THREAD

**Issue by marticrespi** [MichalLytek/type-graphql#560]
**Describe the bug**
Error when I'm trying to generate types.

**To Reproduce**
After install the required packages

````npm i -D typegraphql-prisma````

````npm i dataloader````

I have updated my schema.prisma as suggested:

````
generator client {
  provider = "prisma-client-js"
}

generator typegraphql {
  provider = "node_modules/typegraphql-prisma/generator.js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model BillingAccount {
  businessName       String
  cif                String
  countryCode        String
  createdAt          DateTime
  fiscalAddress      String
  id                 Int                  @default(autoincrement()) @id
  mailingAddress     String
  name               String
  sapCode            String               @unique
  updatedAt          DateTime
  partner            Partner?
  invoice            Invoice[]
  itemBillingAccount ItemBillingAccount[]
}
.............
MORE MODELS
````

I try with next command to generate them

````npx prisma2 generate````

And it throws an error..

````
D:\test-nest-prisma2\node_modules\prisma2\build\index.js
{ Error: TypeError: Cannot read property 'mkdir' of undefined
    at Object.generate [as onGenerate] (D:\test-nest-prisma2\node_modules\typegraphql-prisma\cli\prisma-generator.js:10:25)
    at Object.<anonymous> (D:\test-nest-prisma2\node_modules\@prisma\generator-helper\dist\generatorHandler.js:21:46)
    at Generator.next (<anonymous>)
    at D:\test-nest-prisma2\node_modules\@prisma\generator-helper\dist\generatorHandler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\test-nest-prisma2\node_modules\@prisma\generator-helper\dist\generatorHandler.js:4:12)
    at LineStream.byline_1.default.on (D:\test-nest-prisma2\node_modules\@prisma\generator-helper\dist\generatorHandler.js:17:58)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at GeneratorProcess.handleResponse (D:\test-nest-prisma2\node_modules\prisma2\build\index.js:2:184303)
    at LineStream.s.default.on.e (D:\test-nest-prisma2\node_modules\prisma2\build\index.js:2:183919)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (D:\test-nest-prisma2\node_modules\prisma2\build\index.js:2:898362)
    at LineStream._transform (D:\test-nest-prisma2\node_modules\prisma2\build\index.js:2:898181) code: -32000, data: null }

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```

Explore the full API: http://pris.ly/d/client`
````

It seems that in `prisma-generator.js` file doesn't have the required `fs` package because `fs_1.promises` is undefined.

````
const fs_1 = require("fs");
const path_1 = tslib_1.__importDefault(require("path"));
const generate_code_1 = tslib_1.__importDefault(require("../generator/generate-code"));
const removeDir_1 = tslib_1.__importDefault(require("../utils/removeDir"));
async function generate(options) {
    const outputDir = options.generator.output;
    await fs_1.promises.mkdir(outputDir, { recursive: true });
````

**Expected behavior**
Generate the types successfully.

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node 8.9.4
 - Package version 0.1.5
 - TypeScript version 3.8.3

**Comment by MichalLytek** [comment]
1) Please ask Prisma related question in #217.
2) Node 8 is dead, use Node 10.13+ as only they are supported.
