### ISSUE TITLE
Generating Schema Error. i need help

### ISSUE THREAD

**Issue by jjpark78** [MichalLytek/type-graphql#599]
i have these graphql resolver as follow. 

```typescript
import os from 'os'
import path from 'path'
import {
  Resolver,
  Query,
  FieldResolver,
  Arg,
  Root,
  Mutation,
  Float,
  Int,
  ResolverInterface,
} from 'type-graphql'
import {GraphQLUpload, FileUpload} from 'graphql-upload'
import {Stream} from 'stream'
import {Utils} from '../utils'
import {ScannedImage} from '../schema/image'
import * as AWS from 'aws-sdk'

let uploadFileToS3 = (s3, path) => {
  var pass = new Stream.PassThrough()
  var params = {Bucket: process.env.BUCKET, Key: process.env.KEY + path, Body: pass}
  s3.upload(params, function(err, data) {
    if(err) console.log(err, data)
  })
  return pass
}

@Resolver(of => ScannedImage)
export class ScannedImageResolver {
  @Mutation(returns => ScannedImage)
  uploadImages(@Arg('file', () => GraphQLUpload) file: FileUpload): Promise<ScannedImage>{
    return new Promise(async (resolve, reject) => {
      const {createReadStream, filename} = await file
      //const destinationPath = path.join(os.tmpdir(), filename)
      const s3_location: string = Utils.getS3Location()
      const S3: AWS.S3 = new AWS.S3()
      createReadStream()
        .pipe(uploadFileToS3(S3, s3_location))
        .on('error', () => { return reject()})
        .on('end', () => {
          let result: ScannedImage = new ScannedImage()
          result.storedS3Locatin = s3_location
          result.filename = filename
          console.log(result)
          return resolve(result)
        })
    })
    //return Promise.resolve(true)
  }
}
```

when i try to compile it occurred errors. 

> (node:62968) UnhandledPromiseRejectionWarning: Error: Generating schema error
    at Function.<anonymous> (/Users/jjpark78/개발/JJSOFT/donna/donna-ocr/node_modules/type-graphql/dist/schema/schema-generator.js:20:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jjpark78/개발/JJSOFT/donna/donna-ocr/node_modules/tslib/tslib.js:110:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at main (/Users/jjpark78/개발/JJSOFT/donna/donna-ocr/node_modules/ts-node/src/bin.ts:226:14)
    at Object.<anonymous> (/Users/jjpark78/개발/JJSOFT/donna/donna-ocr/node_modules/ts-node/src/bin.ts:485:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:62968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i really cannot figure out exactly what i'va missing. 

i need help.

**Comment by MichalLytek** [comment]
Your schema need to have at least one query.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
