### ISSUE TITLE
Error on installing dependencies in 1.0.0-rc.1

### ISSUE THREAD

**Issue by rchl** [MichalLytek/type-graphql#624]
**Describe the Bug**
Error on installing dependencies (`npm i`).
After checking out latest version and running `npm i` I got:
```
> type-graphql@0.0.0-unreleased postinstall /Users/me/type-graphql
> node ./dist/postinstall || exit 0

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/me/type-graphql/dist/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN The package @types/node is included as both a dev and production dependency.                                                                                              
```

**To Reproduce**
1) Checkout 1.0.0-rc.1
2) `git clean -fxd` to remove all local artifacts and dependencies that are already installed
3) `npm i`

**Expected Behavior**
No errors

**Environment:**

- OS: OSX
- Node 10.19
- Package version 1.0.0-rc.1

**Additional Context**
The `dist` folder doesn't exist yet. I guess `npm package` creates it.
It shouldn't fail regardless.

**Comment by rchl** [comment]
Not sure how to create dist directory. I've run `npx gulp compile` but with this result:
```
[10:05:46] Requiring external module ts-node/register
[10:05:48] Using gulpfile ~/workspace/github/type-graphql/gulpfile.ts
[10:05:48] Starting 'compile'...
examples/generic-types/paginated-response.type.ts:3:25 - error TS4060: Return type of exported function has or is using private name 'PaginatedResponseClass'.

3 export default function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>) {
                          ~~~~~~~~~~~~~~~~~

examples/generic-types/recipe.resolver.ts:9:31 - error TS4020: 'extends' clause of exported class 'RecipesResponse' has or is using private name 'PaginatedResponseClass'.

9 class RecipesResponse extends PaginatedResponse(Recipe) {
                                ~~~~~~~~~~~~~~~~~~~~~~~~~

examples/resolvers-inheritance/person/person.resolver.ts:23:37 - error TS4020: 'extends' clause of exported class 'PersonResolver' has or is using private name 'ResourceResolverClass'.

23 export class PersonResolver extends ResourceResolver(Person, persons) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

examples/resolvers-inheritance/recipe/recipe.resolver.ts:15:37 - error TS4020: 'extends' clause of exported class 'RecipeResolver' has or is using private name 'ResourceResolverClass'.

15 export class RecipeResolver extends ResourceResolver(Recipe, recipes) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

examples/resolvers-inheritance/resource/resource.resolver.ts:27:17 - error TS4060: Return type of exported function has or is using private name 'ResourceResolverClass'.

27 export function ResourceResolver<TResource extends Resource>(
                   ~~~~~~~~~~~~~~~~


Found 5 errors.

[10:05:55] 'compile' errored after 7.54 s
[10:05:55] Error in plugin "gulp-shell"
Message:
    Command `tsc` failed with exit code 1
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by MichalLytek** [comment]
`Cannot find module '/Users/me/type-graphql/dist/postinstall'` is just an error on internal repo and does not affect production, npm version. You don't need to compile anything nor create a dist folder.

**Comment by rchl** [comment]
I'm investigating another problem and this issue is blocking me.
Do you have at least advice how to handle it? (You must be handling it somehow?).

**Comment by MichalLytek** [comment]
This error does not break anything, it's only about missing script that displays open collective banner after install. You can just ignore that and everything should work.
