### ISSUE TITLE
Showing errors "decorator is not a function" when using class-validator

### ISSUE THREAD

**Issue by shoaibsharif** [MichalLytek/type-graphql#627]
**Describe the Bug**

A Demo could be seen at https://github.com/shoaibsharif/CostCalculator.git under **typegraphql** branch.
When I am trying to use class-validator on InputType(i.e. isEmail, isNotEmpty), I am getting error saying "decorator is not a function"
**To Reproduce**
in InputType I have the following
```js
@InputType()
export class LoginInput implements Partial<User> {
  @Field()
  @isEmail()
  @isNotEmpty()
  email: string;

  @Field()
  @MinLength(5, { message: "Password is too short" })
  password: string;
}
```

But I already get a red squiggles under isEmail() and isNotEmpty() decorator for some reason and when I hover it says it is expecting 1 argument, but according to documentation there should not be any arguments.

**Expected Behavior**
Server should run without any error, and if there is any error on the input type it should give me class validate error.

**Logs**
```bash
node:83106) UnhandledPromiseRejectionWarning: TypeError: decorator is not a function
    at DecorateProperty (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/src/User/user.input.ts:4:92)
    at Object.<anonymous> (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/src/User/user.input.ts:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/qz/1csvdkt10qs096gk_wfds5k80000gn/T/ts-node-dev-hook-3864922883376236.js:57:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at require.extensions.<computed> (/private/var/folders/qz/1csvdkt10qs096gk_wfds5k80000gn/T/ts-node-dev-hook-3864922883376236.js:59:14)
    at Object.nodeDevHook [as .ts] (/Volumes/HardDisk/Practice/JavaScript/react/CostCalculator/backend_ts/node_modules/ts-node-dev/lib/hook.js:61:7)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Environment (please complete the following information):**

- OS: MacOS(10.15.3)
- Node 14.1.0
- Package version 1.0.0-rc-1
- TypeScript version : 3.8.3
- class-validator: 0.12.2

**Additional Context**
When I am using @maxLength or @minLength , it is not giving me any issue but when I am using any validation that doesn't require any argument, it is giving me the issue.

**Comment by shoaibsharif** [comment]
I am really sorry about this. I feel really stupid now. It should be IsEmty() not isEmpty(), I don't know why class-validator was giving me that suggestion. Is it possible I can delete this issue?
