### ISSUE TITLE
FieldResolver stops working when targeting ES5

### ISSUE THREAD

**Issue by diegonc** [MichalLytek/type-graphql#659]
**Describe the Bug**

When targeting ES5,  this @FieldResolver (in the PartyResolver) stops working and throws an exception instead

**To Reproduce**

This repository can be used to reproduce the error: https://github.com/diegonc/test-field-resolver-es5

**Expected Behavior**

The server starts up with the built schema.

**Logs**

```
Error:  Error: Unable to find type metadata for input type or object type named ''
    at /home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/metadata/metadata-storage.js:183:27
    at Array.forEach (<anonymous>)
    at MetadataStorage.buildFieldResolverMetadata (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/metadata/metadata-storage.js:167:21)
    at MetadataStorage.build (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/metadata/metadata-storage.js:100:14)
    at Function.generateFromMetadataSync (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/schema/schema-generator.js:27:51)
    at Function.generateFromMetadata (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/schema/schema-generator.js:15:29)
    at Object.buildSchema (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/utils/buildSchema.js:9:61)
    at Object.buildTypeDefsAndResolvers (/home/diegonc/dev/test/test-field-resolver/node_modules/type-graphql/dist/utils/buildTypeDefsAndResolvers.js:7:40)
    at /home/diegonc/dev/test/test-field-resolver/src/server.ts:14:43
    at step (/home/diegonc/dev/test/test-field-resolver/src/server.ts:33:23)
```

**Environment (please complete the following information):**

- OS: Kubuntu 19.10
- Node v12.16.3
- Package version 1.0.0-rc.2
- TypeScript version 3.9.5
- ts-node v8.10.2

**Additional Context**

This error only popups when the tsconfig is set to target es5. As soon a I bump to es6 it goes away.

**Comment by MichalLytek** [comment]
> TypeGraphQL is designed to work with Node.js LTS (10.3+, 12+) and the latest stable releases. It uses features from ES2018 so we should set our tsconfig.json file appropriately:

https://typegraphql.com/docs/installation.html#typescript-configuration
