### ISSUE TITLE
wont open on OSX.

### ISSUE THREAD

**Issue by BenjaminRasmussen** [MichalLytek/type-graphql#664]
**Describe the Bug**
I get an error telling me to polyfill my fucking server because something in this pacakage wont run with es5-6 and it requires es5-6. I run no business logic, no code literally just importing this breaks my server. Everything else runs fine.

**To Reproduce**
A quick guide how to reproduce the bug.
You can paste here code snippets or even better, provide a link to the repository with minimal reproducible code example.

Import the package

**Expected Behavior**

Nothing, no code is run its just fucking bricked from import

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

[INFO] 15:53:29 Restarting: /Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/main.ts has been modified
Error: Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation instruction for more details.
    at Object.ensureReflectMetadataExists (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/utils.js:41:15)
    at new MetadataStorage (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/metadata-storage.js:26:17)
    at Object.getMetadataStorage (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/getMetadataStorage.js:5:87)
    at Resolver.target (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/decorators/Resolver.js:19:30)
    at __decorate (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:5:95)
    at /Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:10:26
    at Object.<anonymous> (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Module._compile (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/g_/k1bttrxs3hd5h7py17b7wt7r0000gn/T/ts-node-dev-hook-39679732610653184.js:59:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at require.extensions.(anonymous function) (/private/var/folders/g_/k1bttrxs3hd5h7py17b7wt7r0000gn/T/ts-node-dev-hook-39679732610653184.js:61:14)
    at Object.nodeDevHook [as .ts] (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
Using ts-node version 8.10.2, typescript version 3.9.5
Error: Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation instruction for more details.
    at Object.ensureReflectMetadataExists (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/utils.js:41:15)
    at new MetadataStorage (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/metadata-storage.js:26:17)
    at Object.getMetadataStorage (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/metadata/getMetadataStorage.js:5:87)
    at Resolver.target (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/type-graphql/dist/decorators/Resolver.js:19:30)
    at __decorate (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:5:95)
    at /Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:10:26
    at Object.<anonymous> (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/src/domain/user/user.resolver.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Module._compile (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/g_/k1bttrxs3hd5h7py17b7wt7r0000gn/T/ts-node-dev-hook-39679732610653184.js:59:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at require.extensions.(anonymous function) (/private/var/folders/g_/k1bttrxs3hd5h7py17b7wt7r0000gn/T/ts-node-dev-hook-39679732610653184.js:61:14)
    at Object.nodeDevHook [as .ts] (/Users/benjamin/PycharmProjects/VscodeProjects/dinasite/backend/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
[ERROR] 15:53:33 Error: Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation instruction for more details.

**Environment (please complete the following information):**

- OSX
- tsnode 8.10.2
- latest, i used this for less than an hour you can figure it out by the post date
- typescript3.9.5

**Additional Context**

**Comment by MichalLytek** [comment]
> I get an error telling me to polyfill my fucking server because something in this pacakage wont run with es5-6 and it requires es5-6.

You need to install fucking `reflect-metadata` package as described in the fucking installation docs:
https://typegraphql.com/docs/installation.html

This shit also describes that you need to configure your TS to `es2018` and run on the Node.js LTS (10.3+, 12+) that supports this es target.

**Comment by BenjaminRasmussen** [comment]
works like fucking described

**Comment by adventurini** [comment]
Just a note:

If you are running into issues with tsc and trying to run a script, import 'reflect-metadata' directly into the fucking script file.

**Comment by mgonzalezg9** [comment]
Note: 

> Just a note:
> 
> If you are running into issues with tsc and trying to run a script, import 'reflect-metadata' directly into the fucking script file.

Another comment on this: place this import on top to avoid other reflection issues 😬

**Comment by eglove** [comment]
Why isn't this fucking shit on the Prisma site?
https://prisma.typegraphql.com/docs/basics/installation

**Comment by MichalLytek** [comment]
@eglove You need to read this fucking docs properly to make this fucking shit working well:
![image](https://user-images.githubusercontent.com/10618781/142652154-f82272d9-2643-460d-a5e2-87db41dda476.png)

**Comment by eglove** [comment]
Well, fuck me for not reading. Thank you.

**Comment by BlueBazze** [comment]
Sorry for necro, but this just made my fucking day

**Comment by alacret** [comment]
LOL F@cking Thread!

**Comment by galois-dev** [comment]
Let this thread be a cautionary tale. Two years later and this ragepost is still farming the lolz at my expense.

**Comment by novikesumaningtyas** [comment]
Oh my god, this is the first time ever I found such a heart-warming thread, thanks guys for making my day! 2 years later and still the same issue with fucking typegraphql. Error only there when I tried to do jest test, it is working fine in the local run. Solved by import reflect-metadata at the top of files where I registered the enum.

**Comment by kicks321** [comment]
> > I get an error telling me to polyfill my fucking server because something in this pacakage wont run with es5-6 and it requires es5-6.
> 
> You need to install fucking `reflect-metadata` package as described in the fucking installation docs: https://typegraphql.com/docs/installation.html
> 
> This shit also describes that you need to configure your TS to `es2018` and run on the Node.js LTS (10.3+, 12+) that supports this es target.

I mean the docs don't fucking say you need it for JEST testing tho 😉

**Comment by jandve** [comment]
best fucking post ever

**Comment by shubhxg** [comment]
very interesting discussion

**Comment by oyepriyansh** [comment]
here for fun

**Comment by shashankbhat2** [comment]
Spicy thread

**Comment by jaiakash** [comment]
here for fun, from twitter
