### ISSUE TITLE
Can't use authChecker

### ISSUE THREAD

**Issue by shazgames** [MichalLytek/type-graphql#713]
**Describe the Bug**
When I add authChecker(From example in documentation) typescript throws error

**To Reproduce**
```
const schema = await buildSchema({
  resolvers: [UserResolver, AuthResolver],
  authChecker,
})
const server = new ApolloServer({
  schema,
  context: ({ req }) => {
    // console.log(Object.keys(req))
    // console.log(req.headers, req.method)
    console.log(req.headers)

    const ctx: Context = {
      user: {
        id: 5,
        name: "Kekw",
        roles: ["God"],
      },
    }

    return ctx
  },
})
await server.listen(4000)

const authChecker: AuthChecker<Context> = ({ context: { user } }, roles) => {
  if (roles.length === 0) {
    // if `@Authorized()`, check only is user exist
    return user !== undefined
  }
  // there are some roles defined now

  if (!user) {
    // and if no user, restrict access
    return false
  }
  if (user.roles.some((role) => roles.includes(role))) {
    // grant access if the roles overlap
    return true
  }

  // no roles matched, restrict access
  return false
}
```

**Expected Behavior**
Successful code compilation

**Logs**
```
> TSApi@0.0.1 start C:\Users\Provious\Desktop\TSApi\TSApi
> ts-node src/index.ts


C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: тип Unable to compile TypeScript
src\index.ts (35,5): Argument of type '{ resolvers: (typeof UserResolver | typeof AuthResolver)[]; authChecker: AuthChecker<Context, string>; }' is not assignable to parameter of type 'BuildSchemaOptions'.
  Object literal may only specify known properties, and 'authChecker' does not exist in type 'BuildSchemaOptions'. (2345)
    at getOutput (C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:307:15)
    at C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:336:16
    at Object.compile (C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:498:11)
    at Module.m._compile (C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at Object.<anonymous> (C:\Users\Provious\Desktop\TSApi\TSApi\node_modules\ts-node\src\_bin.ts:182:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TSApi@0.0.1 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TSApi@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

**Environment (please complete the following information):**

- OS: Windows 7
- Node: 12.18.3
- Package version: 1.0.0
- TypeScript version: 4.0.3

**Comment by MichalLytek** [comment]
Please make sure that you local and/or global version of typescript and ts-node are the latest one.
This error was reported many times and it's an issue cause by old <3.7 tsc version.

**Comment by shazgames** [comment]
UPDATE
Error occurs if create project with ```typeorm init``` and then install type-graphql. Manually installing typeorm and type-graphql solves error
