### ISSUE TITLE
TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by lavanphat** [MichalLytek/type-graphql#791]
I am having a hard time trying to get a minimal viable example working.

```javascript
import { Field, ID, ObjectType } from 'type-graphql';

@ObjectType()
export class HelloResolver {
  @Field(() => ID)
  readonly id: string;

  @Field()
  title: string;

  @Field({ nullable: true })
  description?: string;

  @Field({ nullable: true })
  averageRating?: number;
}
```
```javascript
import { ApolloServer } from 'apollo-server-express';
import { buildSchemaSync } from 'type-graphql';
import { HelloResolver } from '../graphQL/hello/resolver';

function buildSchema(): any {
  return new ApolloServer({
    schema: buildSchemaSync({
      resolvers: [HelloResolver]
    }),
    context: ({ req, res }) => ({ req, res })
  });
}

export default buildSchema();
```

```javascript
const reflectedType = Reflect.getMetadata(metadataKey, prototype, propertyKey);
                                  ^
TypeError: Reflect.getMetadata is not a function
    at Object.findType (D:\Download\obee-backend-ts\node_modules\type-graphql\dist\helpers\findType.js:9:35)
    at D:\Download\obee-backend-ts\node_modules\type-graphql\dist\decorators\Field.js:16:53
    at __decorate (D:\Download\obee-backend-ts\src\graphQL\hello\resolver.ts:5:110)
    at Object.<anonymous> (D:\Download\obee-backend-ts\src\graphQL\hello\resolver.ts:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)      
    at Module.m._compile (D:\Download\obee-backend-ts\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Download\obee-backend-ts\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

I have found a similar error but cannot be blamed
**Environment (please complete the following information):**

- OS: Window 10
- Node 14
- Package version 1.1.1
- TypeScript version 4.1.5

**Comment by MichalLytek** [comment]
Please read the docs before creating issues:

https://typegraphql.com/docs/installation.html
> the reflect-metadata shim is required to make the type reflection work

**Comment by jcalfee** [comment]
Thanks for this question and answer.  I did just read the docs, ended up hitting this error, and still still unaware that this was related to "reflect-metadata".  I'm integrating this library into a framework that is new to me so there are two moving parts here.  So, @lavanphat, I'm most grateful for your question.
