### ISSUE TITLE
Unable to build federated schema

### ISSUE THREAD

**Issue by bmestanov** [MichalLytek/type-graphql#968]
**Describe the Bug**
`buildFederatedSchema` from the apollo-federation examples fails with `Unable to serialize value '1970-01-01T00:00:00.000Z' as it's not an instance of 'Date'`

**To Reproduce**
```ts
// app.ts
export async function bootstrapAdmin() {
  const adminSchema = await buildFederatedSchema({
    globalMiddlewares: [ErrorInterceptor],
    resolvers: [
      // ...
    ],
  });

  // returns express app with adminServer.applyMiddleware called
  return app;
```

```ts
// index.ts
bootstrapAdmin().then((app) => {
  app.listen(port, () => {
    console.info(`App listening on http://localhost:${port}`);
  });
});
```

```ts
// build-federated-schema.ts
import { specifiedDirectives } from 'graphql';
import federationDirectives from '@apollo/federation/dist/directives';
import gql from 'graphql-tag';
import {
  printSchema,
  buildFederatedSchema as buildApolloFederationSchema,
} from '@apollo/federation';
import { addResolversToSchema, GraphQLResolverMap } from 'apollo-graphql';
import {
  buildSchema,
  BuildSchemaOptions,
  createResolversMap,
} from 'type-graphql';

export async function buildFederatedSchema(
  options: Omit<BuildSchemaOptions, 'skipCheck'>,
  referenceResolvers?: GraphQLResolverMap<any>
) {
  const schema = await buildSchema({
    ...options,
    directives: [
      ...specifiedDirectives,
      ...federationDirectives,
      ...(options.directives || []),
    ],
    skipCheck: true,
  });

  const federatedSchema = buildApolloFederationSchema({
    typeDefs: gql(printSchema(schema)),
    resolvers: createResolversMap(schema) as any,
  });

  if (referenceResolvers) {
    addResolversToSchema(federatedSchema, referenceResolvers);
  }
  return federatedSchema;
}

```

**Expected Behavior**
The correct schema to be built.

**Logs**
```
(node:91120) UnhandledPromiseRejectionWarning: Error: Unable to serialize value '1970-01-01T00:00:00.000Z' as it's not an instance of 'Date'
    at GraphQLScalarType.serialize (/Users/bmestanov/Work/project/node_modules/type-graphql/dist/scalars/isodate.js:18:19)
    at Object.astFromValue (/Users/bmestanov/Work/project/node_modules/graphql/utilities/astFromValue.js:134:27)
    at printInputValue (/Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:350:22)
    at Array.map (<anonymous>)
    at printArgs (/Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:329:23)
    at /Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:282:7
    at Array.map (<anonymous>)
    at printFields (/Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:277:50)
    at printObject (/Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:218:5)
    at printType (/Users/bmestanov/Work/project/node_modules/@apollo/federation/src/service/printFederatedSchema.ts:177:12)
```

**Environment (please complete the following information):**

- OS: macOS 10.14
- Node: 14.16.0
- Package version [e.g. 0.12.2] 1.1.1
- TypeScript version (e.g. 2.8.2) 4.1.5
- graphql 15.5.0
- @apollo/federation 0.22.0

**Additional Context**

**Comment by MichalLytek** [comment]
You can't build the schema or can't execute a query?

Maybe your schema definition is wrong because the graphql iso data scalar requires instance of the `Date` class, while the received value is serialized to string. Same goes to all other scalars like mongo ObjectId, etc.

Maybe you need to put your own graphql scalar for parsing date more liberally (including string and number)

**Comment by bmestanov** [comment]
Can't build the schema.

This is how all my date fields are declared (using the `Date` class)
```ts
  @Field()
  createdAt: Date;

  @Field()
  updatedAt: Date;

  @Field({nullable: true})
  lastOrderAt?: Date;
```

I am able to build the schema with patching the `dist/scalars/isodate.js` file like this:

```js
exports.GraphQLISODateTime = new graphql_1.GraphQLScalarType({
    name: "DateTime",
    description: "The javascript `Date` as string. Type represents date and time as the ISO Date string.",
    serialize(value) {
        if (typeof value === 'string' && Date.parse(value) !== NaN) {
            console.log(value);
            return value;
        }
        if (!(value instanceof Date)) {
            throw new Error(`Unable to serialize value '${value}' as it's not an instance of 'Date'`);
        }
        return value.toISOString();
    },
// ...
```

Log outputs the following:
```
1970-01-01T00:00:00.000Z
2021-08-03T12:35:25.394Z
1970-01-01T00:00:00.000Z
2021-08-03T12:35:25.394Z
Enabling inline tracing for this federated service. To disable, use ApolloServerPluginInlineTraceDisabled.
App listening on http://localhost:3001
```

So the serialize method gets called with the equivalents of `new Date(0).toISOString()` and `new Date().toISOString()` when building the schema.

I can easily use something like `patch-package` to resolve this, but maybe you have a better idea for where to look for, or how to solve it better.

Thanks!

**Comment by MichalLytek** [comment]
> I can easily use something like patch-package to resolve this, but maybe you have a better idea for where to look for, or how to solve it better.

As I said:
> Maybe you need to put your own graphql scalar for parsing date more liberally (including string and number)

https://github.com/excitement-engineer/graphql-iso-date/
https://typegraphql.com/docs/scalars.html#custom-scalars
