### ISSUE TITLE
experimental metadata API polyfill error when using enums

### ISSUE THREAD

**Issue by mazury** [MichalLytek/type-graphql#970]
**Describe the Bug**
I get the error when trying to run prisma query with enum constraints.

**To Reproduce**
A quick guide how to reproduce the bug.
You can paste here code snippets or even better, provide a link to the repository with minimal reproducible code example.

Line of code that breaks:
```
const reportAlreadyInDb = await prisma.report.findMany({ where: { isin, quarter, period: Period.Q, reportType: ReportType.UNIT } })
```

There are no type errors in ide. tsconfig is configurated like in the instruction mentioned in the error message. **It only breaks when I'm adding enum constraint.** 

**Expected Behavior**
App doesn't break with above mentioned error message

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

Error message that shows when the app breaks
```
/home/amz/projects/markethunt/backend/node_modules/type-graphql/dist/metadata/utils.js:42
        throw new errors_1.ReflectMetadataMissingError();
              ^
Error: Looks like you've forgot to provide experimental metadata API polyfill. Please read the installation instruction for more details.
    at Object.ensureReflectMetadataExists (/home/amz/projects/markethunt/backend/node_modules/type-graphql/dist/metadata/utils.js:42:15)
    at new MetadataStorage (/home/amz/projects/markethunt/backend/node_modules/type-graphql/dist/metadata/metadata-storage.js:27:17)
    at Object.getMetadataStorage (/home/amz/projects/markethunt/backend/node_modules/type-graphql/dist/metadata/getMetadataStorage.js:6:87)
    at Object.registerEnumType (/home/amz/projects/markethunt/backend/node_modules/type-graphql/dist/decorators/enums.js:6:26)
    at Object.<anonymous> (/home/amz/projects/markethunt/backend/src/prisma/generated/type-graphql/enums/SortOrder.ts:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/amz/.nvm/versions/node/v14.17.0/lib/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/amz/.nvm/versions/node/v14.17.0/lib/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:933:32)
```

**Environment (please complete the following information):**

- OS: Ubuntu
- Node 14.17
- Package version 1.1.1
- TypeScript version 4.2.3

**Additional Context**

I'm using typegraphql-prisma^0.14.7 package, but the error obviously originates from type-graphql.

**Comment by MichalLytek** [comment]
Please install and configure `reflect-metadata` properly.

**Comment by mazury** [comment]
Install it properly? I mentioned above that I did just that. At least the part that was described in docs. However I'm using the prisma query in a single script and just run it with ts-node. Maybe that's because it's not working? Of course these options are set to true:
```
"experimentalDecorators": true
"emitDecoratorMetadata": true
```

Or maybe it is a bug in typegraphql-prisma package...?
